-- Filthy guild only prio - only set to load if the player is an officer in the guild Filthy on Arugal
-- This is so I can maintain one version of the addon and others can use it :)

-- /script print(GetGuildInfo("player"))

local filthyRealm = "Arugal"
local filthyGuild = "Filthy"
local filthyOfficerRank = 2
local filthyOfficerAltNames = {
	["Mydadishung"] = true,
	["Icantwalk"] = true,
	["Icantrun"] = true,
	["Squirties"] = true,
}
local filthyNickNameClass = {
	["Aaron"] = "warlock",
	["Tobs"] = "deathknight",
	["Koro"] = "paladin",
	["Hawkey"] = "deathknight",
	["Fig"] = "paladin",
	["Chris"] = "druid",
	["Shazz"] = "warlock",
	["Greetings"] = "deathknight",
	["Trisp"] = "warrior",
	["Inkies"] = "rogue",
	["Name"] = "class",
}
local p = FilthyPrio.Player

function FilthyPrio.IsFilthyOfficer()
	if p.realm == filthyRealm and p.guildName == filthyGuild and
		(p.guildRankIndex <= filthyOfficerRank or filthyOfficerAltNames[p.name]) then
		return true
	end
	return false
end

function FilthyPrio.buildOfficerPrio()
	FilthyPrio.Print('You\'re an Officer in Filthy. Loading Ulduar Prios')

	-------------------------
	-- Put prio updates here
	-------------------------

	-- Last updated: 22/03/2023 06:28:56 PM
	FilthyPrio.SetPrio('Band of Lights', '', '', '')
	FilthyPrio.SetPrio('Breastplate of the Timeless', '', '', '')
	FilthyPrio.SetPrio('Dark Matter', '', '', '')
	FilthyPrio.SetPrio('Drape of the Messenger', '', '', '')
	FilthyPrio.SetPrio('Gloves of the Endless Dark', '', '', '')
	FilthyPrio.SetPrio('Meteorite Crystal', '', 'Separate Hpals, replaces EoG for both', '')
	FilthyPrio.SetPrio('Nebula Band', '', '', '')
	FilthyPrio.SetPrio('Observer\'s Mantle', '', '', '')
	FilthyPrio.SetPrio('Pendant of the Somber Witness', '', '', '')
	FilthyPrio.SetPrio('Pulsar Gloves', '', '', '')
	FilthyPrio.SetPrio('Reply-Code Alpha', '', '', '')
	FilthyPrio.SetPrio('Shoulderplates of the Celestial Watch', '', '', '')
	FilthyPrio.SetPrio('Starfall Girdle', '', '', '')
	FilthyPrio.SetPrio('Starlight Treads', '', '', '')
	FilthyPrio.SetPrio('Strength of the Heavens', '', '', '')
	FilthyPrio.SetPrio('Zodiac Leggings', '', '', '')
	FilthyPrio.SetPrio('Boundless Gaze', '', 'BiS: Hunter, Enhance (recon hates the gaze)', '')
	FilthyPrio.SetPrio('Bulwark of Algalon', 'Sluzza', 'Block rating for ToGC', '')
	FilthyPrio.SetPrio('Comet\'s Trail', 'Check sheet', 'BiS: Rogue, Feral, Enhance, Ret, Unholy', 'Verge')
	FilthyPrio.SetPrio('Constellus', 'Ask Ethos', 'Bis non-Valanyr healer 1h, 2nd bis boomy/spriest', 'Thor, Jess')
	FilthyPrio.SetPrio('Cosmos', 'Ask Aaron', 'BiS: Aff, Mages, Spriest, Boomy', 'zef, Cypack')
	FilthyPrio.SetPrio('Legplates of the Endless Void', 'Hawkey', 'BiS: Tanks', 'Hov')
	FilthyPrio.SetPrio('Pharos Gloves', 'Ask Aaron', 'BiS: Aff, Spriest, Mage, Boomy, Ele, HPal', 'Jules, Heasy')
	FilthyPrio.SetPrio('Planewalker Treads', 'RFI/OS', 'Acceptable BiS RSham', 'Cluelust')
	FilthyPrio.SetPrio('Reply-Code Alpha', 'Check sheet > Brickle?', 'BIS! ARP Prio: War/Hunter/Feral/Enh/Rogue/Frost',
		'Aaron, Trisp, Pili, Coonixx')
	FilthyPrio.SetPrio('Sabatons of Lifeless Night', 'Check sheet', 'BiS: Fury, Ret, Frost, Unholy', 'Greetings, Tobs')
	FilthyPrio.SetPrio('Solar Bindings', 'Dof > Trisp > Sandra?', 'BiS: Ass Rogue, Fury', '')
	FilthyPrio.SetPrio('Star-beaded Clutch', 'Chris > Thor', '', '')
	FilthyPrio.SetPrio('Starwatcher\'s Binding', 'Ask Aaron > Disc',
		'BiS: Demo, Aff, Spriest, Mage, Boomy(takes above), Disc', 'Jules')
	FilthyPrio.SetPrio('Fang of Oblivion', 'Inkies Ass?', '', 'Dof Offhand?, Died')
	FilthyPrio.SetPrio('Dreambinder', 'Elguapo > BP ', 'BiS: Feral > Hunter', 'Koonix, Pili, Brick')
	FilthyPrio.SetPrio('Starshard Edge', 'Ask Aaron', 'BiS: Aff, Spriest, Mage, Boomy. Aaron taking Staff', 'Zef')
	FilthyPrio.SetPrio('Skyforge Crossbow', 'elg or brickie > Rogue/War', 'BIS: Hunters > Rogue/War', 'Pili')
	FilthyPrio.SetPrio('Fragment of Val\'anyr', 'Sterile > Jess > Grats Died', 'Legendary Mace', '')
	FilthyPrio.SetPrio('Archaedas\' Lost Legplates', '', '', '')
	FilthyPrio.SetPrio('Chestplate of Titanic Fury', '', '', '')
	FilthyPrio.SetPrio('Cover of the Keepers', '', '', '')
	FilthyPrio.SetPrio('Elemental Focus Stone', '', '', '')
	FilthyPrio.SetPrio('Ironaya\'s Discarded Mantle', '', '', '')
	FilthyPrio.SetPrio('Mantle of the Preserver', '', '', '')
	FilthyPrio.SetPrio('Nimble Climber\'s Belt', '', '', '')
	FilthyPrio.SetPrio('Nurturing Touch', '', '', '')
	FilthyPrio.SetPrio('Raiments of the Corrupted', '', '', '')
	FilthyPrio.SetPrio('Shieldwall of the Breaker', '', '', '')
	FilthyPrio.SetPrio('Amice of the Stoic Watch', 'RFI/OS', 'Filler', 'Cluelust')
	FilthyPrio.SetPrio('Cloak of the Makers', 'Hawkey? > Trisp? > Coonixx? > OS/DE', 'Filler', 'Hov')
	FilthyPrio.SetPrio('Cowl of the Absolute', '', 'BoE, no meta', '')
	FilthyPrio.SetPrio('Gloves of the Stonereaper', 'Inkies? > Coon?', '', '')
	FilthyPrio.SetPrio('Greaves of the Rockmender', 'DE', 'Filler - last drop de\'d', '')
	FilthyPrio.SetPrio('Libram of the Resolute', 'Hov', '', 'Sterile, Jess')
	FilthyPrio.SetPrio('Platinum Band of the Aesir', 'Hov? > Coonixx OS? > Trisp OS? > OS/DE', 'Tank fret ring?',
		'Hawkey')
	FilthyPrio.SetPrio('Ring of the Faithful Servant', 'Ethos > RFI/OS', 'Filler', '')
	FilthyPrio.SetPrio('Sandals of the Ancient Keeper', 'Ask Aaron', 'Those who missed Arcanic Tramplers?', 'Heasy')
	FilthyPrio.SetPrio('Shoulderplates of the Eternal', 'OS/DE', '', 'Sandra')
	FilthyPrio.SetPrio('Unbreakable Chestguard', 'DE', 'Fillter - Last drop de\'d', 'Hov')
	FilthyPrio.SetPrio('Unwavering Stare', 'DE', 'Filler - DE\'d last drop', '')
	FilthyPrio.SetPrio('Runescribed Blade', '', 'Those who missed Turning Tide?', 'Oxi')
	FilthyPrio.SetPrio('Siren\'s Cry', 'Elguapo > Mr Pole', '', 'brick')
	FilthyPrio.SetPrio('Stonerender', 'Msg Offhand? > Tobs', '', 'Msg')
	FilthyPrio.SetPrio('Belt of the Iron Servant', '', '', '')
	FilthyPrio.SetPrio('Boots of the Petrified Forest', '', '', '')
	FilthyPrio.SetPrio('Circlet of True Sight', '', '', '')
	FilthyPrio.SetPrio('Cloak of the Iron Council', '', '', '')
	FilthyPrio.SetPrio('Greaves of Iron Intensity', '', '', '')
	FilthyPrio.SetPrio('Lady Maye\'s Sapphire Ring', '', '', '')
	FilthyPrio.SetPrio('Leggings of Swift Reflexes', '', '', '')
	FilthyPrio.SetPrio('Rune-Etched Nightblade', '', '', '')
	FilthyPrio.SetPrio('Runetouch Wristwraps', '', '', '')
	FilthyPrio.SetPrio('Stormtip', '', '', '')
	FilthyPrio.SetPrio('Belt of the Crystal Tree', '', '', '')
	FilthyPrio.SetPrio('Loop of the Agile', '', '', '')
	FilthyPrio.SetPrio('Watchful Eye of Fate', '', '', '')
	FilthyPrio.SetPrio('Perilous Bite', '', '', '')
	FilthyPrio.SetPrio('The Masticator', '', '', '')
	FilthyPrio.SetPrio('Ancient Iron Heaume', '', '', '')
	FilthyPrio.SetPrio('Drape of the Lithe', 'Verge? > Died? > Elg?', 'Filler - Rogue/Feral/Hunter/Enh',
		'Inkies, Brickle, BP')
	FilthyPrio.SetPrio('Handguards of the Enclave', 'DE', 'Block rating for ToGC', 'Hov, Trispirus')
	FilthyPrio.SetPrio('Insurmountable Fervor', '', 'Filler - Frost/Ret/Unholy/Fury', 'Msg, Sandra')
	FilthyPrio.SetPrio('Iron-studded Mantle', '', 'Hunter/Enh filler', 'Pili')
	FilthyPrio.SetPrio('Overload Legwraps', '', 'Who missed out on Malygos hit legs?', 'Aaron')
	FilthyPrio.SetPrio('Phaelia\'s Vestments of the Sprouting Seed', 'Chris/DE',
		'Filler, replaced by bought Tier 8 token', '')
	FilthyPrio.SetPrio('Radiant Seal', 'Sterile? > RFI/OS', 'Filler - check with Ethos', 'Cluelust, Jess, Chris, ')
	FilthyPrio.SetPrio('Raiments of the Iron Council', 'RFI/DE', 'Filler', 'Aaron, Oxi')
	FilthyPrio.SetPrio('Runed Ironhide Boots', 'Trisp? > Coonixx if no crafted > Coonixx Tank',
		'Fillter - Last drop de\'d', '')
	FilthyPrio.SetPrio('Runeshaper\'s Gloves', 'DE', '', '')
	FilthyPrio.SetPrio('Steelbreaker\'s Embrace', 'Sandra to drop hit?', '', '')
	FilthyPrio.SetPrio('Unblinking Eye', '', '', '')
	FilthyPrio.SetPrio('Rapture', 'RFI/DE', 'Filler, give to those who didnt get a Naxx weapon?', 'Heasy')
	FilthyPrio.SetPrio('Stormrune Edge', '', 'Fillter - Last drop de\'d', '')
	FilthyPrio.SetPrio('Belt of Colossal Rage', 'Tobs > Greetings', 'BiS: Frost, Unholy', 'Msg')
	FilthyPrio.SetPrio('Drape of Mortal Downfall', 'Ask Aaron - because he doesn\'t update the sheet',
		'BiS: Ele, Boomy, Fire', 'Heasy')
	FilthyPrio.SetPrio('Greaves of Swift Vengeance', 'Hunters', 'BiS: Hunters (all have 2nd bis)', 'Died')
	FilthyPrio.SetPrio('Sapphire Amulet of Renewal', '', 'BiS: Demo, Arcane, RDruid', '')
	FilthyPrio.SetPrio('Shoulderpads of the Intruder', 'Koro > RFI/OS/DE', 'BiS: Feral, Rogue',
		'Dof, Inkies, Big Feral Coon')
	FilthyPrio.SetPrio('Chestguard of the Lasher', '', '', '')
	FilthyPrio.SetPrio('Gloves of the Wayward Conqueror', '', '', '')
	FilthyPrio.SetPrio('Gloves of the Wayward Protector', '', '', '')
	FilthyPrio.SetPrio('Gloves of the Wayward Vanquisher', '', '', '')
	FilthyPrio.SetPrio('Ironbark Faceguard', '', '', '')
	FilthyPrio.SetPrio('Legplates of Flourishing Resolve', '', '', '')
	FilthyPrio.SetPrio('Tunic of the Limber Stalker', '', '', '')
	FilthyPrio.SetPrio('Unraveling Reach', '', '', '')
	FilthyPrio.SetPrio('Fire Orchid Signet', '', '', '')
	FilthyPrio.SetPrio('Gloves of Whispering Winds', '', '', '')
	FilthyPrio.SetPrio('Seed of Budding Carnage', '', '', '')
	FilthyPrio.SetPrio('Petrified Ivy Sprig', '', 'ethos and aaron in different runs THANKS', '')
	FilthyPrio.SetPrio('Serilas, Blood Blade of Invar One-Arm', '', '', '')
	FilthyPrio.SetPrio('Boots of the Servant', 'RFI/DE', 'Filler', 'Jules')
	FilthyPrio.SetPrio('Gauntlets of Ruthless Reprisal', 'Tobs UH?', 'BiS: Unholy', 'Msg')
	FilthyPrio.SetPrio('Leggings of the Lifetender', 'Chris > RFI/OS', '', '')
	FilthyPrio.SetPrio('Legplates of the Wayward Conqueror', 'Zef Healing > OS/DE',
		'Spriest > Disc > Ret > Demo > Aff > HPal', 'Zef, Koro, Koro, Cypack, Jess, Sterile, Ethos, Aaron, Oxi, ')
	FilthyPrio.SetPrio('Legplates of the Wayward Protector', 'Cluelust DPS > OS/DE', 'Ele > RSham > Enh > Hunter',
		'Thor, Cluelust, Died, Brickie, Elguapo, Pili')
	FilthyPrio.SetPrio('Legplates of the Wayward Vanquisher', 'New druids? > Hawkey DPS > OS/DE',
		'Mage > Boomy > RDruid > DK', 'Heasy, Jules, Chris, Tobs, Msg, Chris Resto, Greetings, Inkies, ')
	FilthyPrio.SetPrio('Nymph Heart Charm', 'BoE Sell', 'BoE', '')
	FilthyPrio.SetPrio('The Lifebinder', 'RDI/DE', 'Filler', 'Chris, Oxi')
	FilthyPrio.SetPrio('Bladetwister', 'Inkies Offhand > DE', 'BiS: Assassin x2, Combat offhand', 'Dof, Dof Offhand')
	FilthyPrio.SetPrio('Bronze Pendant of the Vanir', 'Trisp OS > Coonixx OS > Greetings OS', 'BiS Mitigation',
		'Hov, Hawkey')
	FilthyPrio.SetPrio('Drape of the Sullen Goddess', 'Sterile > Cluelust > Jess > OS/RFI',
		'BiS by ilvl except for RDruid', 'Ethos')
	FilthyPrio.SetPrio('Handguards of Revitalization', 'Hawkey? > Trisp OS > Greetings OS > OS/DE', '', 'Hov')
	FilthyPrio.SetPrio('Leggings of the Enslaved Idol', 'Ask Aaron', 'BiS: Arcane, Boomy', 'Icantwalk')
	FilthyPrio.SetPrio('Avalanche', '', '', '')
	FilthyPrio.SetPrio('Cowl of Icy Breaths', '', '', '')
	FilthyPrio.SetPrio('Leggings of the Wayward Conqueror', '', '', '')
	FilthyPrio.SetPrio('Leggings of the Wayward Protector', '', '', '')
	FilthyPrio.SetPrio('Leggings of the Wayward Vanquisher', '', '', '')
	FilthyPrio.SetPrio('Signet of Winter', '', '', '')
	FilthyPrio.SetPrio('Stormedge', '', '', '')
	FilthyPrio.SetPrio('Winter\'s Frigid Embrace', '', '', '')
	FilthyPrio.SetPrio('Bitter Cold Armguards', '', '', '')
	FilthyPrio.SetPrio('Icecore Staff', '', '', '')
	FilthyPrio.SetPrio('Ice Layered Barrier', '', '', '')
	FilthyPrio.SetPrio('Shiver', '', '', '')
	FilthyPrio.SetPrio('The Boreal Guard', '', '', '')
	FilthyPrio.SetPrio('Breastplate of the Wayward Conqueror', 'Zef Heals? > Bin it',
		'Shadow > Disc > Ret > Demo > Aff > HPal', 'Zeforr, Ethos, Sandra, Aaron, Cypack, Sterile, Jess')
	FilthyPrio.SetPrio('Breastplate of the Wayward Protector', 'Mr Pole > Bin it', 'Ele > RSham > Enh > Warrior > Hunter',
		'Thor, Cluelust, Died, Trisp, Brickie, Pili, Trisp Tank, Died OS')
	FilthyPrio.SetPrio('Breastplate of the Wayward Vanquisher', 'Bin it',
		'Hawkey > Mage > Boomy > Feral?* > Frost > Unholy > Rogue > RDruid',
		'Jules, Hawkey, Heasy, Chris, Chris Resto, Greetings, Tobs, Msg, Inkies, Verge, Coonixx, Chris Feral')
	FilthyPrio.SetPrio('Frost-bound Chain Bracers', 'Sandra?', 'Filler - upgrade for Koro', 'Elguapo')
	FilthyPrio.SetPrio('Frostplate Greaves', 'RFI/OS', 'Filler - last drop de\'d', '')
	FilthyPrio.SetPrio('Frozen Loop', 'RFI/DE', 'Filler', 'Zeforr, Heasy')
	FilthyPrio.SetPrio('Northern Barrier', 'Hov for the MAD FRET > Trisp OS > Pally OS? > DE', '', '')
	FilthyPrio.SetPrio('Winter\'s Icy Embrace', 'DE', 'Filler - Last one was DE\'d', '')
	FilthyPrio.SetPrio('Bindings of Winter Gale', 'Thor > HPals > Died?', 'BiS Ele, RSham, HPal, also good for Enh???',
		'Cluelust')
	FilthyPrio.SetPrio('Drape of Icy Intent', 'Dof > Died', 'BiS Rogue, Enhance', 'Inkies')
	FilthyPrio.SetPrio('Frigid Strength of Hodir', 'Greetings > Tobs > Trisp > Msg', 'BiS: Frost - 2nd BiS: Fury/Unholy',
		'')
	FilthyPrio.SetPrio('Gloves of the Frozen Glade', 'Chris', '', '')
	FilthyPrio.SetPrio('Staff of Endless Winter', 'Ask', 'BiS 2h for some casters', 'Jules, Heasy')
	FilthyPrio.SetPrio('Armbraces of the Vibrant Flame', '', '', '')
	FilthyPrio.SetPrio('Drape of Fuming Anger', '', '', '')
	FilthyPrio.SetPrio('Furnace Stone', '', '', '')
	FilthyPrio.SetPrio('Gauntlets of the Iron Furnace', '', '', '')
	FilthyPrio.SetPrio('Gloves of Smoldering Touch', '', '', '')
	FilthyPrio.SetPrio('Igniter Rod', '', '', '')
	FilthyPrio.SetPrio('Pauldrons of Tempered Will', '', '', '')
	FilthyPrio.SetPrio('Relentless Edge', '', '', '')
	FilthyPrio.SetPrio('Rifle of the Platinum Guard', '', '', '')
	FilthyPrio.SetPrio('Shawl of the Caretaker', '', '', '')
	FilthyPrio.SetPrio('Charred Saronite Greaves', 'Hawkey? > Trisp OS? > Greetings OS?', '', 'Hov')
	FilthyPrio.SetPrio('Cindershard Ring', 'Verge > Check with hunters', 'Hit ring - Filler for Rogue/Feral/Hunter',
		'Koonix, Inkies')
	FilthyPrio.SetPrio('Flamestalker Boots', '', '', 'Coonixx if no crafted')
	FilthyPrio.SetPrio('Flamewrought Cinch', 'RFI/DE', 'Filler - last drop was DE\'d', '')
	FilthyPrio.SetPrio('Girdle of Embers', 'Tobs > Hawkey DPS', 'Filler Frost/Unholy', 'Greetings')
	FilthyPrio.SetPrio('Heart of Iron', 'Died to stay alive?  > Trisp/Coonixx OS', 'Big fucken stam - anyone but Hawkey',
		'Hov, Hawkey')
	FilthyPrio.SetPrio('Helm of the Furnace Master', 'DE', 'Filler hunter - last drop de\'d', '')
	FilthyPrio.SetPrio('Lifeforge Breastplate', 'BoE Sell', 'BoE', '')
	FilthyPrio.SetPrio('Pyrelight Circle', '', 'Filler but ok, give to people who missed KT ring?', 'Cypack, Cluelust')
	FilthyPrio.SetPrio('Soot-Covered Mantle', 'RFI/DE', 'Filler - DE\'d last drop', 'Cypack, Shazz')
	FilthyPrio.SetPrio('Totem of the Dancing Flame', 'Died?', 'DE\'d last drop', '')
	FilthyPrio.SetPrio('Wristguards of the Firetender', 'HPal/OS? > DE', 'Filler', 'Cluelust, Died')
	FilthyPrio.SetPrio('Intensity', '', 'Filler, Hit, probs still an UG for a few', '')
	FilthyPrio.SetPrio('Scepter of Creation', '', 'Filler', 'oxi')
	FilthyPrio.SetPrio('Worldcarver', 'OS/DE', 'Fillter - Last drop de\'d', 'Msg')
	FilthyPrio.SetPrio('Emerald Signet Ring', '', '', '')
	FilthyPrio.SetPrio('Greaves of the Earthbinder', '', '', '')
	FilthyPrio.SetPrio('Mark of the Unyielding', '', '', '')
	FilthyPrio.SetPrio('Pendant of the Piercing Glare', '', '', '')
	FilthyPrio.SetPrio('Sabatons of the Iron Watcher', '', '', '')
	FilthyPrio.SetPrio('Shawl of the Shattered Giant', '', '', '')
	FilthyPrio.SetPrio('Shoulderguards of the Solemn Watch', '', '', '')
	FilthyPrio.SetPrio('Spark of Hope', '', '', '')
	FilthyPrio.SetPrio('Spire of Withering Dreams', '', '', '')
	FilthyPrio.SetPrio('Stoneguard', '', '', '')
	FilthyPrio.SetPrio('Bracers of Unleashed Magic', 'Ask Aaron', 'Filler, who missed out on Unsullied and needs hit?',
		'Zef, Ethos DPS, Jules')
	FilthyPrio.SetPrio('Gloves of the Pythonic Guardian', '', 'Filler until T8', 'Sterile, Jess')
	FilthyPrio.SetPrio('Handwraps of Plentiful Recovery', '', 'Filler', '')
	FilthyPrio.SetPrio('Idol of the Crying Wind', 'DE', 'Shithouse - DE this fucker', 'Chris')
	FilthyPrio.SetPrio('Ironmender', 'RFI/DE', 'Good, most want Cosmos off Algalon',
		'Ethos, Aaron, Zef Heals, Chris, Oxi')
	FilthyPrio.SetPrio('Leggings of the Stoneweaver', 'OS/RFI', 'Filler', '')
	FilthyPrio.SetPrio('Necklace of Unerring Mettle', 'Trisp Tank > Pally OS? > DE', 'Block rating for ToGC', 'Hov')
	FilthyPrio.SetPrio('Robes of the Umbral Brute', '', 'Filler, all casters use T8 chest as BiS', '')
	FilthyPrio.SetPrio('Saronite Plated Legguards', '', '', 'Hov')
	FilthyPrio.SetPrio('Shoulderpads of the Monolith', 'Verge? > RFI/DE', 'Fillter Feral/Rogue', 'Inkies, Coonixx')
	FilthyPrio.SetPrio('Unfaltering Armguards', 'HPals', '', '')
	FilthyPrio.SetPrio('Wrathstone', 'RFI/DE', 'Filler ', 'Sandra, Died, Pili')
	FilthyPrio.SetPrio('Giant\'s Bane', 'Rogue/War?', 'Fillter - Hunters have better, rogues/wars?', 'Elg')
	FilthyPrio.SetPrio('Malice', 'RFI/DE', 'Filler - Frost > Unholy > Combat', 'Hawkey DPS')
	FilthyPrio.SetPrio('Decimator\'s Armguards', 'Sandra?', 'Fillter - minor upgrade for Sandra', 'greetings')
	FilthyPrio.SetPrio('Combustion Bracers', '', '', '')
	FilthyPrio.SetPrio('Energy Siphon', '', '', '')
	FilthyPrio.SetPrio('Firesoul', '', '', '')
	FilthyPrio.SetPrio('Firestrider Chestguard', '', '', '')
	FilthyPrio.SetPrio('Flamewatch Armguards', '', '', '')
	FilthyPrio.SetPrio('Ironsoul', '', '', '')
	FilthyPrio.SetPrio('Kinetic Ripper', '', '', '')
	FilthyPrio.SetPrio('Lifespark Visage', '', '', '')
	FilthyPrio.SetPrio('Might of the Leviathan', '', '', '')
	FilthyPrio.SetPrio('Pyrite Infuser', '', '', '')
	FilthyPrio.SetPrio('Gilded Steel Legplates', '', '', '')
	FilthyPrio.SetPrio('Handguards of Potent Cures', '', '', '')
	FilthyPrio.SetPrio('Mantle of Fiery Vengeance', '', '', '')
	FilthyPrio.SetPrio('Shimmering Seal', '', '', '')
	FilthyPrio.SetPrio('Twirling Blades', '', '', '')
	FilthyPrio.SetPrio('Constructor\'s Handwraps', '', 'Filler', '')
	FilthyPrio.SetPrio('Embrace of the Leviathan', 'RFI/DE', 'Filler - last drop de\'d', 'Aaron')
	FilthyPrio.SetPrio('Freya\'s Choker of Warding', 'RFI/OS', 'Filler', 'Sterile, Jess, Cluelust, Ethos')
	FilthyPrio.SetPrio('Gloves of the Fiery Behemoth', 'RFI/DE', 'Filler - Hunter', 'Elguapo')
	FilthyPrio.SetPrio('Glowing Ring of Reclamation', 'RFI', 'Filler', 'Ethos')
	FilthyPrio.SetPrio('Iron Riveted War Helm', 'RFI/DE', 'Filler', 'msg')
	FilthyPrio.SetPrio('Leviathan Fueling Manual', 'RFI/DE', 'Hit OH', 'Shazz, Oxi, Ethos DPS, Jules')
	FilthyPrio.SetPrio('Mechanist\'s Bindings', 'Sandra?', 'Filler - upgrade for Koro', '')
	FilthyPrio.SetPrio('Mimiron\'s Inferno Couplings', 'Trisp OS? > OS/DE', '', 'Hov, Hawkey')
	FilthyPrio.SetPrio('Steamcaller\'s Totem', 'Died OS > DE', 'BiS Resto Sham', 'Cluelust')
	FilthyPrio.SetPrio('Steamworker\'s Goggles', 'DE', 'Filler - Last drop was DE\'d', '')
	FilthyPrio.SetPrio('Strength of the Automaton', 'Tobs? > Msg? > RFI/DE', 'Filler for Fury, Frost, Unholy, Ret',
		'Trisp, Sandra, Greetings')
	FilthyPrio.SetPrio('The Leviathan\'s Coil', '', '', '')
	FilthyPrio.SetPrio('Rising Sun', 'Inkies', 'Filler for Rogues', 'Dof')
	FilthyPrio.SetPrio('Titanguard', 'Hawkey? > RFI/DE', 'Filler tank wep', 'Hov, Trisp Tank')
	FilthyPrio.SetPrio('Boots of Fiery Resolution', 'Ask Aaron > Ethos > Chris Resto',
		'BiS Demo, Aff, Spriest, Arcane, Disc, RDruid', 'Aaron, Oxi')
	FilthyPrio.SetPrio('Golden Saronite Dragon', 'Verge for Cumbat? > trisp for prot pvp kekw > Bin it',
		'BIS Combat and Enhance', 'Inkies, Died')
	FilthyPrio.SetPrio('Pendant of Fiery Havoc', 'Ask Aaron', 'BiS: Casters casting spells n shit', 'Cypack, Jules, Oxi')
	FilthyPrio.SetPrio('Plated Leggings of Ruination', 'dk > koro > Check sheet', 'BiS: Ret, Frost, Unholy', '')
	FilthyPrio.SetPrio('Shoulderpads of Dormant Energies', 'RFI/DE', 'Filler', 'Chris, Hors')
	FilthyPrio.SetPrio('Cable of the Metrognome', '', '', '')
	FilthyPrio.SetPrio('Helm of the Wayward Conqueror', '', '', '')
	FilthyPrio.SetPrio('Helm of the Wayward Vanquisher', '', '', '')
	FilthyPrio.SetPrio('Pulse Baton', '', '', '')
	FilthyPrio.SetPrio('Static Charge Handwraps', '', '', '')
	FilthyPrio.SetPrio('Stylish Power Cape', '', '', '')
	FilthyPrio.SetPrio('Helm of the Wayward Protector', '', '', '')
	FilthyPrio.SetPrio('Shoulderguards of Assimilation', '', '', '')
	FilthyPrio.SetPrio('Fused Alloy Legplates', '', '', '')
	FilthyPrio.SetPrio('Greaves of the Iron Army', '', '', '')
	FilthyPrio.SetPrio('Mimiron\'s Flight Goggles', '', '', '')
	FilthyPrio.SetPrio('Tempered Mercury Greaves', '', '', '')
	FilthyPrio.SetPrio('Fusion Blade', '', '', '')
	FilthyPrio.SetPrio('Asimov\'s Drape', 'BoE Sell', 'BoE', 'Jules, Heasy')
	FilthyPrio.SetPrio('Gauntlets of the Wayward Conqueror', 'Aaron? > OS/DE', 'Ret > Demo > HPals',
		'Sandra, Jess, Sterile, Ethos, ')
	FilthyPrio.SetPrio('Gauntlets of the Wayward Protector', 'OS/DE', 'RSham > Enh > Warr > Hunter',
		'Trisp, Died, Elguapo, Pili, Bricko, Trisp OS, Cluelust, Died OS')
	FilthyPrio.SetPrio('Gauntlets of the Wayward Vanquisher', 'OS/DE', 'Hawkey > Feral > Frost > Ass > RDruid',
		'Hawkey, Coonixx, Greetings, Tobs, Inkies, Verge, Chris Resto, Hawkey DPS, Jules')
	FilthyPrio.SetPrio('Pandora\'s Plea', 'Jess > Chris? > RFI/OS', 'Good not great, better on short fights',
		'Cluelust, Sterile')
	FilthyPrio.SetPrio('Waistguard of the Creator', '', 'Filler - last drop de\'d', '')
	FilthyPrio.SetPrio('Malleable Steelweave Mantle', 'Chris really wants this > RFI/DE', '', '')
	FilthyPrio.SetPrio('Insanity\'s Grip', 'DE', 'Filler - Enh/Combat', 'Verge Combat')
	FilthyPrio.SetPrio('Delirium\'s Touch', 'Inkies?', '', '')
	FilthyPrio.SetPrio('Armbands of Bedlam', 'Check sheet - probs Sandra', 'BiS: Frost, Unholy, Ret', 'Msg')
	FilthyPrio.SetPrio('Conductive Seal', 'Ask Aaron', 'BiS: Demo, Aff, Mage, Boomy, Spriest, Ele, Disc', 'Thor, Cypack')
	FilthyPrio.SetPrio('Crown of Luminescence', 'Ask Aaron', 'BiS Demo, Aff, Arcane, Boomy', 'Cypack, Oxi')
	FilthyPrio.SetPrio('Titanskin Cloak', '', '', '')
	FilthyPrio.SetPrio('Band of Draconic Guile', '', '', '')
	FilthyPrio.SetPrio('Binding of the Dragon Matriarch', '', '', '')
	FilthyPrio.SetPrio('Bracers of the Smothering Inferno', '', '', '')
	FilthyPrio.SetPrio('Breastplate of the Afterlife', '', '', '')
	FilthyPrio.SetPrio('Dragonsteel Faceplate', '', '', '')
	FilthyPrio.SetPrio('Eye of the Broodmother', '', '', '')
	FilthyPrio.SetPrio('Ironscale Leggings', '', '', '')
	FilthyPrio.SetPrio('Razorscale Talon', '', '', '')
	FilthyPrio.SetPrio('Stormtempered Girdle', '', '', '')
	FilthyPrio.SetPrio('Treads of the Invader', '', '', '')
	FilthyPrio.SetPrio('Belt of the Fallen Wyrm', 'DE', 'All shamans have this, probs DE', 'Thor , Cluelust, Died')
	FilthyPrio.SetPrio('Bracers of the Broodmother', '', '', '')
	FilthyPrio.SetPrio('Collar of the Wyrmhunter', '', 'Filler, lots of hit', 'Oxi')
	FilthyPrio.SetPrio('Dragonslayer\'s Brace', 'Trisp OS?', 'Block rating for ToGC', 'Hov')
	FilthyPrio.SetPrio('Drape of the Drakerider', 'OS/DE', 'Filler - Fury > Frost > Unholy',
		'Trisp, Greetings, Tobs, Sandra')
	FilthyPrio.SetPrio('Libram of Discord', 'OS/DE', 'Not the best', 'Sandra')
	FilthyPrio.SetPrio('Living Flame', 'RFI/DE', 'Aaron then those who didnt get Dying Curse?', 'Oxi, Jules, Bipbop')
	FilthyPrio.SetPrio('Proto-hide Leggings', 'BoE Sell', 'BoE', '')
	FilthyPrio.SetPrio('Razorscale Shoulderguards', 'DE', 'Fillter - last drop de\'d', 'Hov OS, Jess')
	FilthyPrio.SetPrio('Saronite Mesh Legguards', 'Trisp? > RFI/DE', 'Filler - all hunters have',
		'Elguapo, Brickie, Pili')
	FilthyPrio.SetPrio('Shackles of the Odalisque', 'RFI/DE', '2nd BiS, give to those without Unsullied Cuffs?',
		'Cypack, Ethos, Oxi, Bipbop')
	FilthyPrio.SetPrio('Sigil of Deflection', 'OS/DE', '', 'Hawkey')
	FilthyPrio.SetPrio('Guiding Star', 'Sterile > RFI/OS', 'Filler, People who missed out on KT Torch',
		'Jess, Cluelust/Ethos, Thor')
	FilthyPrio.SetPrio('Remorse', 'RFI/DE', '', 'Msg')
	FilthyPrio.SetPrio('Veranus\' Bane', 'Trisp Tanking?', '', '')
	FilthyPrio.SetPrio('Belt of the Blood Pit', '', '', '')
	FilthyPrio.SetPrio('Guise of the Midgard Serpent', '', '', '')
	FilthyPrio.SetPrio('Handwraps of Resonance', '', '', '')
	FilthyPrio.SetPrio('Legacy of Thunder', '', '', '')
	FilthyPrio.SetPrio('Leggings of Unstable Discharge', '', '', '')
	FilthyPrio.SetPrio('Spaulders of the Wayward Conqueror', '', '', '')
	FilthyPrio.SetPrio('Spaulders of the Wayward Protector', '', '', '')
	FilthyPrio.SetPrio('Spaulders of the Wayward Vanquisher', '', '', '')
	FilthyPrio.SetPrio('Gauntlets of the Thunder God', '', '', '')
	FilthyPrio.SetPrio('Mjolnir Runestone', '', '', '')
	FilthyPrio.SetPrio('Pendant of the Shallow Grave', '', '', '')
	FilthyPrio.SetPrio('Sif\'s Remembrance', '', '', '')
	FilthyPrio.SetPrio('Combatant\'s Bootblade', '', '', '')
	FilthyPrio.SetPrio('Belt of the Betrayed', 'DE', 'Hunters all have crafted', '')
	FilthyPrio.SetPrio('Crown of the Wayward Conqueror', 'Bin it', 'Prot > Shadow > Disc > Ret?* > HPal',
		'Hov, Zef, ethos, Jess, Sterile, Zef Heals, Cypack, Aaron, Oxigas, Ethos Shadow')
	FilthyPrio.SetPrio('Crown of the Wayward Protector', 'Bin it', 'Getting binned',
		'Thor, Cluelust, Trisp, Brickie, Pili, Elg, Mr Pole, Cluelust DPS, Trisp Tank, Died, Died OS')
	FilthyPrio.SetPrio('Crown of the Wayward Vanquisher', 'Coon Daddy? > DKs Tanking? > Bin it',
		'Hawkey > Mage?* > Boomy?* > Feral > Frost > Ass > RDruid',
		'Hawkey, Chris, Tobs, Heasy, Jules, Greetings, Verge, Chris Resto, Hawkey DPS')
	FilthyPrio.SetPrio('Leggings of Lost Love', '', 'Filler', '')
	FilthyPrio.SetPrio('Scale of Fates', 'Ask Aaron > RSham', 'BiS: Aff, Spriest, Mage, Boomy, RSham', 'Jules, Cypack')
	FilthyPrio.SetPrio('Sif\'s Promise', 'RFI/DE', 'Solid filler for Ret, Unholy, Frost, Fury', 'Tobs, Msg, Hawkey')
	FilthyPrio.SetPrio('Vulmir, the Northern Tempest', 'Hawkey DPS', '2nd BiS Frost until 10m Hard Mode',
		'Tobs, Tobs x2, Died')
	FilthyPrio.SetPrio('Embrace of the Gladiator', 'Check sheet', 'BiS: Feral, Assassin, Combat, Survival', 'Elguapo')
	FilthyPrio.SetPrio('Fate\'s Clutch', 'Hawkey > Trisp OS > Coonixx OS > OS/DE', 'BiS: Tanks', 'Hov')
	FilthyPrio.SetPrio('Pauldrons of the Combatant', '', 'Filler - last drop de\'d', '')
	FilthyPrio.SetPrio('Warhelm of the Champion', 'Greetings > Tobs (way too much hit) > Hawkey DPS',
		'BiS: Ret, Unholy > Frost', 'Sandra, Msg')
	FilthyPrio.SetPrio('Wisdom\'s Hold', 'Sterile', 'Only 25man Caster Shield, BiS Resto, HPal, Ele',
		'Thor, Cluelust, Jess')
	FilthyPrio.SetPrio('Bindings of the Depths', '', '', '')
	FilthyPrio.SetPrio('Choker of the Abyss', '', '', '')
	FilthyPrio.SetPrio('Darkstone Ring', '', '', '')
	FilthyPrio.SetPrio('Gauntlets of the Wretched', '', '', '')
	FilthyPrio.SetPrio('Hoperender', '', '', '')
	FilthyPrio.SetPrio('Pendant of Endless Despair', '', '', '')
	FilthyPrio.SetPrio('Saronite Animus Cloak', '', '', '')
	FilthyPrio.SetPrio('Shadowbite', '', '', '')
	FilthyPrio.SetPrio('Underworld Mantle', '', '', '')
	FilthyPrio.SetPrio('Vestments of the Piercing Light', '', '', '')
	FilthyPrio.SetPrio('Drape of the Faceless General', '', '', '')
	FilthyPrio.SetPrio('Leggings of Profound Darkness', '', '', '')
	FilthyPrio.SetPrio('Aesuga, Hand of the Ardent Champion', '',
		'Probs thor? Ele sham gets really shafted with weapons this phase', '')
	FilthyPrio.SetPrio('Tortured Earth', '', '', '')
	FilthyPrio.SetPrio('Void Sabre', '', '', '')
	FilthyPrio.SetPrio('Belt of Clinging Hope', 'RFI/OS', 'Filler', 'Jess')
	FilthyPrio.SetPrio('Belt of the Darkspeaker', 'DE', 'Filler, crafted belts are better', '')
	FilthyPrio.SetPrio('Boots of the Forgotten Depths', 'RFI/DE', 'Filler - all shams have this', 'Cluelust, Thor, Died')
	FilthyPrio.SetPrio('Boots of the Underdweller', 'DE', 'Filler - last drop de\'d', '')
	FilthyPrio.SetPrio('Darkcore Leggings', 'hunter', 'BoE', '')
	FilthyPrio.SetPrio('Grips of the Unbroken', 'Chris? > RFI/DE', 'Filler - last drop de\'d', '')
	FilthyPrio.SetPrio('Helm of the Faceless', 'Greetings OS? > OS/DE', '', 'Trisp OS')
	FilthyPrio.SetPrio('Idol of the Corruptor', 'DE', '', 'Coonixx, Chris')
	FilthyPrio.SetPrio('Libram of the Sacred Shield', 'Pally OS? > DE', '', 'Hov')
	FilthyPrio.SetPrio('Mantle of the Unknowing', 'DE', 'Filler - last drop de\'d', '')
	FilthyPrio.SetPrio('Metallic Loop of the Sufferer', 'RFI/DE', 'Filler for Enh, Rogue, Hunter, Pally', 'Verge, Died')
	FilthyPrio.SetPrio('Ring of the Vacant Eye', 'RFI/DE', 'Who missed Naxx rings and needs hit?', 'Aaron, Oxi')
	FilthyPrio.SetPrio('The General\'s Heart', 'RFI/DE', 'Farming spec', 'Hov, Hawkey')
	FilthyPrio.SetPrio('Scepter of Lost Souls', '', 'BiS caster non-hit wand?', '')
	FilthyPrio.SetPrio('Lotrafen, Spear of the Damned', 'Elguapo?', 'Hunter 2nd BiS', 'Brickie')
	FilthyPrio.SetPrio('Flare of the Heavens', 'Ask Aaron', 'BiS: Demo, Aff, Mage, Spriest, Boomy',
		'Aaron , Heasy, Zef, Jules')
	FilthyPrio.SetPrio('Handwraps of the Vigilant', '', 'BiS: Disc, filler until Pharos for Spriest/casters?', '')
	FilthyPrio.SetPrio('Pendulum of Infinity', 'Check sheet/current necks > hunter - maybe brickle',
		'BiS: Rogue, Feral, Hunter, Enhance, Fury, Ret', '')
	FilthyPrio.SetPrio('Vestments of the Blind Denizen', 'OS/RFI', 'BiS: RDruid', 'Chris')
	FilthyPrio.SetPrio('Voldrethar, Dark Blade of Oblivion', 'Trisp', '', 'Trisp , Sandra')
	FilthyPrio.SetPrio('Armbands of the Construct', '', '', '')
	FilthyPrio.SetPrio('Chestplate of Vicious Potency', '', '', '')
	FilthyPrio.SetPrio('Conductive Cord', '', '', '')
	FilthyPrio.SetPrio('Gloves of Taut Grip', '', '', '')
	FilthyPrio.SetPrio('Helm of Veiled Energies', '', '', '')
	FilthyPrio.SetPrio('Plasma Foil', '', '', '')
	FilthyPrio.SetPrio('Power Enhancing Loop', '', '', '')
	FilthyPrio.SetPrio('Pulsing Spellshield', '', '', '')
	FilthyPrio.SetPrio('Treacherous Shoulderpads', '', '', '')
	FilthyPrio.SetPrio('Vest of the Glowing Crescent', '', '', '')
	FilthyPrio.SetPrio('Breastplate of the Stoneshaper', '', '', '')
	FilthyPrio.SetPrio('Fluxing Energy Coils', '', '', '')
	FilthyPrio.SetPrio('Seal of Ulduar', '', '', '')
	FilthyPrio.SetPrio('Aesir\'s Edge', '', '', '')
	FilthyPrio.SetPrio('Magnetized Projectile Emitter', '', '', '')
	FilthyPrio.SetPrio('Boots of Hasty Revival', 'RFI/DE', '', 'Chris')
	FilthyPrio.SetPrio('Brass-lined Boots', 'RFI/DE', 'Filler - last drop de\'d', 'Elguapo, Died')
	FilthyPrio.SetPrio('Clockwork Legplates', 'Greetings', 'Filler', '')
	FilthyPrio.SetPrio('Crazed Construct Ring', 'Msg > Greetings? > Tobs? > Hawkey DPS?', 'BiS: Unholy', '')
	FilthyPrio.SetPrio('Horologist\'s Wristguards', '', 'Filler - last drop de\'d', '')
	FilthyPrio.SetPrio('Mantle of Wavering Calm', 'DE', 'Filler - Previously DE\'d', 'Aaron, Oxi')
	FilthyPrio.SetPrio('Quartz-studded Harness', 'DE', 'Filler - Previously DE\'d', 'Cluelust, Died OS')
	FilthyPrio.SetPrio('Sandals of Rash Temperament', '', 'Decent filler, Hit', '')
	FilthyPrio.SetPrio('Shoulderplates of the Deconstructor', 'DE', 'Filler - Previously DE\'d', '')
	FilthyPrio.SetPrio('Sigil of the Vengeful Heart', 'Tobs OS > OS/DE', '', 'Msg, Hawkey the known PvPer')
	FilthyPrio.SetPrio('Signet of the Earthshaker', 'OS/DE', 'Block rating for ToGC?', 'Hov, Trisp OS')
	FilthyPrio.SetPrio('Thunderfall Totem', 'RFI/DE', 'Quite dogshit. PvP maybe?', 'Thor')
	FilthyPrio.SetPrio('Golem-Shard Sticker', 'Inkies Ass?', '', 'Dof')
	FilthyPrio.SetPrio('Quartz Crystal Wand', '', 'Filler, Who needs hit?', '')
	FilthyPrio.SetPrio('Twisted Visage', 'Hunter', 'BP has Betrayer - Brickie/Elg have Journey\'s End', '')
	FilthyPrio.SetPrio('Breastplate of the Devoted', 'DE', 'BiS Holy Pal - both have so can DE', 'Jess, Sterile')
	FilthyPrio.SetPrio('Charm of Meticulous Timing', 'Jess > Ethos > Zef OS',
		'BiS all healers except Resto Druid, give pumpers', 'Mindblown, Sterile')
	FilthyPrio.SetPrio('Gloves of the Steady Hand', 'Hunters first - maybe pili', 'BiS: Hunter > Ret > Unholy', '')
	FilthyPrio.SetPrio('Grasps of Reason', 'Ask Aaron', 'BiS: Demo, Aff, Spriest, Mage, Boomy, Disc', 'Heasy, Aaron')
	FilthyPrio.SetPrio('Sorthalis, Hammer of the Watchers', 'Hov > Hawkey?',
		'BiS: Pally Tank - Hov needs for ToGC block set', 'Trisp OS')
	FilthyPrio.SetPrio('Abaddon', '', '', '')
	FilthyPrio.SetPrio('Chestguard of the Wayward Conqueror', '', '', '')
	FilthyPrio.SetPrio('Chestguard of the Wayward Protector', '', '', '')
	FilthyPrio.SetPrio('Chestguard of the Wayward Vanquisher', '', '', '')
	FilthyPrio.SetPrio('Deliverance', '', '', '')
	FilthyPrio.SetPrio('Devotion', '', '', '')
	FilthyPrio.SetPrio('Faceguard of the Eyeless Horror', '', '', '')
	FilthyPrio.SetPrio('Kingsbane', '', '', '')
	FilthyPrio.SetPrio('Leggings of the Insatiable', '', '', '')
	FilthyPrio.SetPrio('Pendant of a Thousand Maws', '', '', '')
	FilthyPrio.SetPrio('Royal Seal of King Llane', '', '', '')
	FilthyPrio.SetPrio('Touch of Madness', '', '', '')
	FilthyPrio.SetPrio('Treads of the Dragon Council', '', '', '')
	FilthyPrio.SetPrio('Amice of Inconceivable Horror', '', '', '')
	FilthyPrio.SetPrio('Signet of Soft Lament', '', '', '')
	FilthyPrio.SetPrio('Soul-Devouring Cinch', '', '', '')
	FilthyPrio.SetPrio('Vanquished Clutches of Yogg-Saron', '', '', '')
	FilthyPrio.SetPrio('Caress of Insanity', '', '', '')
	FilthyPrio.SetPrio('Blood of the Old God', 'Dof? > Sandra? (maybe too much hit)',
		'Filler for Rogue, Enhance, Frost, Ret', 'Inkies?, Died')
	FilthyPrio.SetPrio('Chestguard of Insidious Intent', 'Hunters', 'Aaron\'s favourite guild', 'BP')
	FilthyPrio.SetPrio('Chestguard of the Fallen God', 'Thor > OS/RFI', '', 'Cluelust')
	FilthyPrio.SetPrio('Cowl of Dark Whispers', '', 'Filler', 'Aaron')
	FilthyPrio.SetPrio('Garona\'s Guise', '', '', 'inkies, Koonixx')
	FilthyPrio.SetPrio('Godbane Signet', 'Died? > RFI/DE', 'Filler Rogue/Ret/Enhance/Feral', 'sandra, dof')
	FilthyPrio.SetPrio('Mantle of the Wayward Conqueror', 'Zef Heals > OS/DE', 'Prot > Shadow > Disc > Ret > Demo > HPal',
		'Hov, zef, Ethos, Aaron, Jess, Sandra, Sterile, Oxi')
	FilthyPrio.SetPrio('Mantle of the Wayward Protector', 'Cluelust (has 10) > Pili or Elg? > Cluelust DPS',
		'Ele > RSham > Enh > Warrior > Hunter', 'Thor, Died, Trisp')
	FilthyPrio.SetPrio('Mantle of the Wayward Vanquisher', 'Chris Resto > Hawkey DPS > DK Tank sets',
		'Hawkey > Mage > Boomy > Feral?* > Frost > Unholy > RDruid',
		'Hawkey, Jules, Greetings, Heasy, Msg, Tobs, Chris, Coonixx (for set, but not bis)')
	FilthyPrio.SetPrio('Sanity\'s Bond', 'Sterile/Jess/Cluelust whoever needs rings > RFI/OS',
		'Filler, arguably worse than Auiraya ring', '')
	FilthyPrio.SetPrio('Shawl of Haunted Memories', 'RFI/DE', 'Filler', 'Zeforr, Oxi')
	FilthyPrio.SetPrio('Soulscribe', '', 'Filler, who needs 239 weapons still?', '')
	FilthyPrio.SetPrio('Earthshaper', 'OS/DE', '', 'Sandra, Trisp?')
	FilthyPrio.SetPrio('Hammer of Crushing Whispers', '', '', '')
	FilthyPrio.SetPrio('Dark Edge of Depravity', 'Hunter', 'BP has Betrayer - Brickie/Elg have Journey\'s End',
		'Sandra, elg, Papa Coon for Tanking?')
	FilthyPrio.SetPrio('Legguards of Cunning Deception', 'Trisp > Check sheet',
		'BiS: Rogue, Feral, Hunter, Fury - Trisp going to make the leather wearers cry', '')
	FilthyPrio.SetPrio('Seal of the Betrayed King', 'Trisp', 'BiS: Frost, Unholy, Ret',
		'Tobs, Greetings, Msg, Sandra, Hawkey DPS')
	FilthyPrio.SetPrio('Show of Faith', 'Chris/Mindblown > Ethos', 'BiS: Disc > RDruid > RSham', '')
	FilthyPrio.SetPrio('Treads of the False Oracle', 'Ask Aaron - because he doesn\'t update the sheet',
		'BiS: Boomy, Ele, Fire', 'Jules')
	FilthyPrio.SetPrio('Mimiron\'s Head', '', '', 'Jess, Cypack,dof')
	FilthyPrio.SetPrio('Belt of the Sleeper', 'DE', 'Filler - last drop de\'d', '')
	FilthyPrio.SetPrio('Bladebearer\'s Signet', '', 'Filler - last drop de\'d', 'Hawkey')
	FilthyPrio.SetPrio('Daschal\'s Bite', '', 'I\'d bite daschal', '')
	FilthyPrio.SetPrio('Greaves of the Stonewarder', 'OS/DE', 'Shield tanks', 'Hov, Trisp OS')
	FilthyPrio.SetPrio('Grips of Chaos', '', 'DE\'d last drop', '')
	FilthyPrio.SetPrio('Idol of the Flourishing Life', 'RFI/DE', '', 'Chris')
	FilthyPrio.SetPrio('Leggings of the Tortured Earth', '', '', 'Died')
	FilthyPrio.SetPrio('Pendant of Focused Energies', '', 'Filler - last drop de\'d', '')
	FilthyPrio.SetPrio('Relic Hunter\'s Cord', 'koonix?', '', 'Inkies')
	FilthyPrio.SetPrio('Shoulders of Misfortune', '', 'Hunters?', 'Pili')
	FilthyPrio.SetPrio('Shroud of Alteration', 'Ask Ethos', '', 'Sterile, Chris')
	FilthyPrio.SetPrio('Titanstone Pendant', '', '', '')
end
