-- Filthy guild only prio - only set to load if the player is an officer in the guild Filthy on Arugal
-- This is so I can maintain one version of the addon and others can use it :)

local realmName = GetRealmName()
local guildName, guildRankName, guildRankIndex, realm = GetGuildInfo("player")
local playerName, playerRealm = UnitName("player")
local filthyRealm = "Arugal"
local filthyGuild = "Filthy"
local filthyOfficerRank = 2
local filthyNames = {
	["Mydadishung"] = true,
	["Icantwalk"] = true,
	["Icantrun"] = true,
	["Squirties"] = true,
}
local filthyNickNameClass = {
	["Aaron"] = "warlock",
	["Tobs"] = "deathknight",
	["Koro"] = "paladin",
	["Hawkey"] = "deathknight",
	["Fig"] = "paladin",
	["Chris"] = "druid",
	["Shazz"] = "warlock",
	["Greetings"] = "deathknight",
	["Trisp"] = "warrior",
	["Inkies"] = "rogue",
	["Name"] = "class",
}
-- /script print(GetGuildInfo("player"))
if realmName == filthyRealm and guildName == filthyGuild and
	(guildRankIndex <= filthyOfficerRank or filthyNames[playerName]) then
	print(colorString('Loot Prio:', 'green') .. ' Hi ' .. playerName)
	print(colorString('Loot Prio:', 'green') .. ' You\'re an Officer in Filthy. Sup?')
	-- Put prio updates here

	-- Last updated: 08/12/2022 06:06:54 PM
	set_prio('Cloak of Averted Crisis', 'DE', 'Filler', 'Thor, Chris, Fig OS, Jules')
	set_prio('Shawl of the Old Maid', 'OS/DE', 'Filler', 'Aaron, Shazz')
	set_prio('Shroud of Luminosity', 'RFI/DE', '', 'Thor, Jules, Samme')
	set_prio('Cloak of the Shadowed Sun', 'OS/DE', 'badge cloak is bis> armour set', 'Coonixx OS')
	set_prio('Thunderstorm Amulet', '', '', 'Shazz')
	set_prio('Lost Jewel', 'RFI/DE', 'BIS: Boomy, Demo', 'Chris, Aaron, Samme, Jules')
	set_prio('Seized Beauty', 'DE', '', 'Ethos, Cluelust')
	set_prio('Dying Curse', 'Samme', 'BiS for every caster to save hit elsewhere', 'Aaron, Cypack, Thor, Heasy, Chris')
	set_prio('Forethought Talisman', 'Ask Jess? > OS/DE', 'BiS throughput after Illustration of the Dragon Soul',
		'Ethos, Cluelust, Sterile')
	set_prio('Heritage', 'OS/DE', 'Slight upgrade over badge neck', 'Coonixx, Tobs, Hovden, Greetings')
	set_prio('Fool\'s Trial', '', 'Filler until Quest neck - prio people last in line',
		'Sandra, Elguapo, Msg, Sterile OS, Tobs UH')
	set_prio('Sand-Worn Band', '', 'Better than JC ring but not bis', 'Fig, Hawkey')
	set_prio('Ruthlessness', 'Sandra > Coonixx? > OS/DE', 'BIS: Frost & Unholy', 'Tobs, Greetings, Msg, Trisp, hawkey')
	set_prio('Strong-Handed Ring', 'OS/DE', 'BiS: Hunter, Rogue', 'Inkeyes, Verge, Beanpole, Pili, Died, Elguapo, Chris OS')
	set_prio('Defender\'s Code', 'Hov/Coon?', 'bear OS maybe', 'Trisp OS')
	set_prio('Grim Toll', 'Coonixx > Greetings > Tobs', 'BIS: Feral, Warrior, Frost DK', 'Trisp, Hovden')
	set_prio('Shadow of the Ghoul', 'OS', 'Block set Fig > OS', 'Trisp')
	set_prio('Boots of the Escaped Captive', 'DE', 'Minor upgrade over Wyrmrest exalted boots', 'Chris')
	set_prio('Ousted Bead Necklace', 'DE', 'Badge neck is better.', '')
	set_prio('Haunting Call', '', 'Whoever needs it at the time', '')
	set_prio('Silent Crusader', 'Greetings > Tobs > Hawkey', 'Frost DK > Unholy > Rogue', 'Greetings, Tobs')
	set_prio('Shoulderpads of the Undaunted', 'DE', 'Possibly Koro for the hit', '')
	set_prio('Inevitable Defeat', 'OS/DE', 'Hawkey > the rest', 'Hawkey')
	set_prio('Corpse Scarab Handguards', 'DE', 'Filler', 'Cluelust')
	set_prio('Rescinding Grips', 'DE', 'Worse than tier gloves', '')
	set_prio('Leggings of Atrophy', 'OS/DE', 'Filler', '')
	set_prio('Chains of Adoration', 'Sterile', 'BiS non-quest neck RSham and HPal', 'Cluelust, Jess')
	set_prio('Shield of Assimilation', 'Cluelust > Sterile', 'Second BiS RSham, HPal and Ele', 'Jess')
	set_prio('Mantle of the Locusts', 'RFI/DE', 'BiS: RDruid', 'Shazz')
	set_prio('Sash of the Parlor', 'OS/DE', 'Filler', 'Ethos')
	set_prio('Gemmed Wand of the Nerubians', '', 'BiS:Arcane Mage/Spriest', 'Zlips, Zeforr, Samme, Jules')
	set_prio('Swarm Bindings', '', 'Filler', '')
	set_prio('Dawnwalkers', 'Inkies > Koro', 'BIS: Rogue', 'Verge')
	set_prio('Inexorable Sabatons', 'OS/DE', 'Fig then OS', 'Fig, Trisp OS')
	set_prio('Sabatons of Sudden Revival', 'Tobs > Msg', 'BIS: Unholy', '')
	set_prio('Webbed Death', 'Hunters', 'BIS Rogues and Hunter DW', 'inkies, dof')
	set_prio('Pauldrons of Unnatural Death', 'OS/DE', 'hawkey', 'Hawkey, Trisp OS')
	set_prio('Arachnoid Gold Band', '', '', 'Pili')
	set_prio('Cult\'s Chestguard', '', 'Filler', '')
	set_prio('Tunic of Prejudice', '', '', '')
	set_prio('Atonement Greaves', 'OS/DE', 'Filler', 'Thor')
	set_prio('Gloves of Token Respect', '', 'Arcane Bis - But who first?', 'Heasy')
	set_prio('Faerlina\'s Madness', 'DE', 'No meta.', '')
	set_prio('Epaulets of the Grieving Servant', 'DE', 'Filler', '')
	set_prio('Belt of False Dignity', '', 'Filler', '')
	set_prio('DE', 'OS/DE', 'Also from Boj?', '')
	set_prio('Punctilious Bindings', '', '', 'Samme, Shazz')
	set_prio('Dislocating Handguards', 'Check with Ferals first', 'Filler for Feral, Rogues', 'Inkeyes')
	set_prio('Callous-Hearted Gauntlets', 'OS', 'avoidance set maybe, not bis over tier', 'Hawkey')
	set_prio('Fire-Scorched Greathelm', 'DE', 'No meta poop', '')
	set_prio('Widow\'s Fury', 'Msg?', 'Unholy fillter?', 'Tobs')
	set_prio('Idol of Worship', 'DE', 'Also from Boj?', 'Coonixx')
	set_prio('Bracers of the Tyrant', '', 'BIS Frost - (Greetings needs for expertise cap)', 'Tobs, Greetings')
	set_prio('Aged Winter Cloak', '', 'BIS War and maybe Feral', 'Trisp, Coonixx, Hov')
	set_prio('Undiminished Battleplate', 'DE', 'Filler', '')
	set_prio('Digested Silken Robes', 'DE', '', '')
	set_prio('Quivering Tunic', 'OS/DE', 'Filler', 'Cluelust ')
	set_prio('Cowl of the Perished', '', '', '')
	set_prio('Helm of Diminished Pride', 'DE', 'Bad', '')
	set_prio('Distorted Limbs', '', '', '')
	set_prio('Wraith Strike', '', '', 'Died')
	set_prio('Matriarch\'s Spawn', '', 'Demo/Aff', 'Aaron, Cypack, Azz')
	set_prio('Mantle of Scattered Kinship', 'OS/DE', '', 'Chris')
	set_prio('Infectious Skitterer Leggings', 'DE', '', 'Coonixx')
	set_prio('The Jawbone', 'OS/DE', 'BIS Ret AoE or something... (because overall damage is bis)', 'Koro')
	set_prio('Torn Web Wrapping', 'Beanpole > Elguapo', 'BIS Hunter?', 'Pili')
	set_prio('Ablative Chitin Girdle', 'Hawkey > Trisp OS > OS/DE', 'BIS: Prot Pal > Blood DK > Prot War', 'Fig')
	set_prio('Sinner\'s Bindings', 'Hovden > Rogues with Dawnwalkers', 'BiS: Feral, Rogue', 'Coonixx')
	set_prio('Bindings of the Hapless Prey', 'Trisp OS > OS/DE', '', 'Fig')
	set_prio('Gloves of Calculated Risk', 'DE', 'Hunter filler', 'Pili')
	set_prio('Crude Discolored Battlegrips', 'Sterile? > OS/DE', 'Filler', 'Trisp, Koro')
	set_prio('Boots of Septic Wounds', '', '', '')
	set_prio('Boots of Persuasion', '', '', 'Samme')
	set_prio('Surplus Limb', 'Samme > Jules', 'Arcane mage/Spriest', 'Heasy')
	set_prio('Waistguard of Divine Grace', 'Sterile > Saicere > RFI', 'Super minor for both', '')
	set_prio('Libram of Tolerance', 'DE', 'meh', '')
	set_prio('Girdle of the Gambit', 'DE', 'bis RSham', 'Cluelust, Thor')
	set_prio('Sash of Solitude', 'Ethos > RFI', '', '')
	set_prio('Totem of Hex', '', '', 'Died, Cluelust')
	set_prio('Hero\'s Surrender', 'DE', '', 'Jolie')
	set_prio('Split Greathammer', 'dks? > trisp tank wep?', 'Unholy fillter?', 'msg')
	set_prio('Arrowsong', '', 'Physical next? Pretty sure beanpole has it', 'Beanpole')
	set_prio('Belt of the Tortured', 'Sandra > Coonixx if needs hit > trisp arms', 'ret/rogue bis - prio rogue',
		'Inkeyes, Verge, Hovden')
	set_prio('Fleshless Girdle', '', 'block set but most likely wasted item', '')
	set_prio('Tunic of Indulgence', '', 'Filler', 'Coonixx')
	set_prio('Chestguard of the Exhausted', '', 'tier just better both tanks OS', '')
	set_prio('Fallout Impervious Tunic', 'DE', '', 'Thor')
	set_prio('Cowl of Vanity', 'RFI', '', 'Zlips, Samme, Heasy')
	set_prio('Desecrated Past', 'OS/DE', '', '')
	set_prio('Plague Igniter', '', '', '')
	set_prio('Sympathetic Amice', 'RFI/DE', '', '')
	set_prio('Mantle of the Fatigued Sage', '', '', '')
	set_prio('Spaulders of Incoherence', 'RFI/DE', 'worse than tier', '')
	set_prio('Bracers of Liberation', 'Jess if no Valor bracers', '', '')
	set_prio('Twilight Mist', '', 'Rogue / Hunter filler?', '')
	set_prio('Origin of Nightmares', '', 'fillter - prio kitties', '')
	set_prio('Depraved Linked Belt', 'Beanpole', 'BIS: Hunter, Enhance - 2nd bis?', 'Pili, Died, Elguapo')
	set_prio('Girdle of Chivalry', 'Tobs > Koro until leather belt?', 'BIS Unholy > Frost DK - depending on setup, ret',
		'Msg, Greetings')
	set_prio('Slime Stream Bands', 'Elguapo', 'BIS: Hunter, Enhance', 'Beanpole, Pili, Died')
	set_prio('Sabatons of Endurance', 'Hawkey', 'both tanks bis   fig>hawkey', 'Fig')
	set_prio('Cover of Silence', 'DE', 'No meta', '')
	set_prio('Riveted Abomination Leggings', 'Tobs', 'BIS Unholy', 'Msg')
	set_prio('Benefactor\'s Gauntlets', 'BoE Sell', 'BoE', 'Died')
	set_prio('Wraps of the Persecuted', 'RFI/DE', '', 'Zeforr')
	set_prio('Faceguard of the Succumbed', 'DE/OS', '', 'Jess, Sterile')
	set_prio('Headpiece of Fungal Bloom', 'DE', '', 'Chris')
	set_prio('Pauldrons of the Abandoned', 'DE', '', '')
	set_prio('Spire of Sunset', 'RFI/DE', '', 'Cluelust')
	set_prio('Cincture of Polarity', 'Thor', '', '')
	set_prio('Legplates of the Lost Conqueror', '', 'Prot > Holy > RFI', 'Fig, Jess, Sterile x 2, Koro, Shazz, Fig OS')
	set_prio('Legplates of the Lost Protector', '', 'Enhance > Hunter > Resto > Fury',
		'Died, Beanpole, Pili, Cluelust, Trisp OS, Elguapo, Died OS')
	set_prio('Legplates of the Lost Vanquisher', '', 'Frost DK > Rogue > Mage',
		'Greetings, Tobs, Inkies, Verge, Jules, Heasy, Samme, Coonixx, Hawkey, Msg OS, Chris OS')
	set_prio('Tunic of Masked Suffering', 'RFI/DE', 'Filler', 'Beanpole, Elguapo')
	set_prio('Crippled Treads', '', 'Filler hunter / enh', 'Aaron?, Died')
	set_prio('Gauntlets of the Disobedient', '', 'block set', '')
	set_prio('Robes of Mutation', 'DE', '', '')
	set_prio('Poignant Sabatons', 'Sell', 'BoE', 'Sterile, Jess')
	set_prio('Gloves of the Fallen Wizard', '', '', '')
	set_prio('Legguards of the Undisturbed', 'RFI', '', '')
	set_prio('Accursed Spine', 'RFI', '', 'Chris, Ethos')
	set_prio('Belt of Potent Chanting', '', '', '')
	set_prio('Bands of Impurity', '', '', 'Cypack, Zlips')
	set_prio('Libram of Radiance', 'DE', '', '')
	set_prio('Angry Dread', 'Greetings > Tobs > Greetings > Tobs', 'BIS Frost dks', '')
	set_prio('Shoulderguards of Opportunity', '', 'People looking for the next opportunity', '')
	set_prio('Spinning Fate', 'dof', 'good hit option for thrown, consult war/rogue', 'Trisp, Inkies')
	set_prio('Thrusting Bands', 'Any rogues/feral need expertise/hit?', '', 'Koro')
	set_prio('Breastplate of Tormented Rage', '', 'not better than tier', '')
	set_prio('Iron-Spring Jumpers', '', 'BoE item - decent hit piece for warr/dk', '')
	set_prio('Leggings of Colossal Strides', 'OS/DE', '', '')
	set_prio('Eruption-Scarred Boots', 'OS/DE', 'Filler', '')
	set_prio('Chestguard of Bitter Charms', 'OS/DE', 'bad', '')
	set_prio('Heigan\'s Putrid Vestments', 'ask me', 'BIS: Spriest', '')
	set_prio('Serene Echoes', 'OS/DE', '', 'Shazz')
	set_prio('Gloves of the Dancing Bear', 'DE', '', '')
	set_prio('Helm of Pilgrimage', 'DE', 'no meta', '')
	set_prio('Legguards of the Apostle', 'OS/DE', '', 'Koro')
	set_prio('Bindings of the Decrepit', 'OS/DE', '', 'Cluelust, Died OS')
	set_prio('Sigil of Awareness', 'Hawkey > Msg', 'BIS Frost DK', 'Greetings, Tobs')
	set_prio('Cryptfiend\'s Bite', 'Hunters/DE', 'fillter - prio kitties', 'Elguapo')
	set_prio('The Undeath Carrier', 'OS/DE', 'fillter - prio kitties', 'Coonixx, Hov, Elguapo')
	set_prio('Stalk-Skin Belt', 'Ferals > Trisp', 'BIS: Feral, Arms', '')
	set_prio('Footwraps of Vile Deceit', 'Verge? > OS/DE', 'BiS: Feral', 'hov, coonixx, Inkies')
	set_prio('Grotesque Handgrips', 'OS/DE', 'Filler', 'Beanpole')
	set_prio('Greaves of Turbulence', '', 'block set', 'Trisp')
	set_prio('The Hand of Nerub', '', 'Hunter filler?', '')
	set_prio('Vest of Vitality', 'OS/DE', '', '')
	set_prio('Boots of Impetuous Ideals', '', 'BoE', 'Jules')
	set_prio('Cowl of Innocent Delight', 'DE', 'no meta', '')
	set_prio('The Impossible Dream', '', '', '')
	set_prio('Girdle of Unity', 'DE', '', '')
	set_prio('Fading Glow', 'OS/DE', '', 'Zeforr')
	set_prio('Mantle of the Lost Conqueror', 'OS', 'Prot > ?? (Holy, Ret, Disc, Shadow, Demo, Aff)',
		'Fig, Sandra, Aaron, Ethos, Sterile, Jess, Cypack, Shazz, Jess OS')
	set_prio('Mantle of the Lost Protector', 'RFI or OS > OS', 'Enhance > ?? (Arms, Hunter, Resto)',
		'Died, Trisp, Cluelust, Pili, Beanpole, Died, Thor OS')
	set_prio('Mantle of the Lost Vanquisher', '', 'Balance > Frost DK > Blood DK > Rogue > Mage',
		'Chris, Greetings, Tobs, Hovden, Samme, Verge, Hawkey?, Inkies, Jules, Heasy, Chris OS, Coonixx OS')
	set_prio('Chestpiece of Suspicion', '', 'Filler for suspicious folk', 'Verge')
	set_prio('Legplates of Double Strikes', '', 'BiS Arms/Fury', 'Trisp')
	set_prio('Boots of Forlorn Wishes', 'ethos will take these if aaron doesnt give to casters', '', '')
	set_prio('Faithful Steel Sabatons', 'OS/DE', '', '')
	set_prio('Gauntlets of Guiding Touch', 'OS/DE', 'Good but Hpals run tier', '')
	set_prio('Girdle of Recuperation', 'OS/DE', 'Ele Shaman', 'Cluelust, Died')
	set_prio('Bands of Mutual Respect', '', 'Ele Shaman', 'Thor')
	set_prio('Bindings of the Expansive Mind', '', 'Filler', 'Shazz')
	set_prio('Esteemed Bindings', '', '', 'Chris')
	set_prio('Idol of the Shooting Star', 'DE', '', '')
	set_prio('Spaulders of Egotism', 'Sell', 'BoE', '')
	set_prio('Shoulderpads of Secret Arts', 'OS/DE', '', '')
	set_prio('Totem of Dueling', '', 'legitimate duelers only', 'Died?')
	set_prio('Girdle of Razuvious', 'Tobs > Trisp', 'BiS Arms/Frost DK', '')
	set_prio('Bracers of the Unholy Knight', '', 'BIS: dk > not in figs set', 'Hawkey')
	set_prio('Hood of the Exodus', 'Rogue/War?', 'Filler', 'Coonixx, Hov')
	set_prio('Helm of Vital Protection', '', 'pretty decent helm very similar to tier but 4pc', 'Trisp')
	set_prio('Leggings of Fleeting Moments', 'DE', '', '')
	set_prio('Leggings of Failed Escape', 'Pili', 'BiS: Hunter', 'Beanpole, Elguapo')
	set_prio('Libram of Resurgence', 'DE', '', 'Fig')
	set_prio('Gothik\'s Cowl', '', '', '')
	set_prio('Helm of Unleashed Energy', 'OS/DE', 'Filler for Rsham until Tier', 'Cluelust, Thor')
	set_prio('Life and Death', 'Azz', '', 'Samme, Cypack, Sterile')
	set_prio('Shackled Cinch', 'DE', '', '')
	set_prio('Idol of Awakening', 'OS/DE', '', 'Chris')
	set_prio('Touch of Horror', 'OS/DE', '', '')
	set_prio('Abetment Bracers', 'Sterile', '', 'Jess')
	set_prio('Bindings of Yearning', 'Sell', 'Prot > Demo > Aff > Ret > Holy', '')
	set_prio('Burdened Shoulderplates', 'Fig', 'block set', '')
	set_prio('Bracers of Unrelenting Attack', 'Msg > Trisp?', 'BIS Unholy, Arms, Frost - depending on setup', '')
	set_prio('Breastplate of the Lost Conqueror', 'Sterile OS', 'Tank > DPS > Healer',
		'Fig, Aaron, Cypack, Koro, Jess, Sterile')
	set_prio('Breastplate of the Lost Protector', '', 'Enhance > Ele > Resto > Arms',
		'Died, Thor, Cluelust, Trisp?, bean, Elguapo, Pili')
	set_prio('Breastplate of the Lost Vanquisher', '',
		'Balance > Blood DK > Frost/Unholy > Rogue > Mage (Give 10 man to Mage > Rogue)',
		'Chris, Hawkey, Msg, Greetings, Tobs, Inkies, Verge, Samme, Coonixx')
	set_prio('Zeliek\'s Gauntlets', 'Tobs', 'BiS Unholy DK/decent for fury', 'Msg')
	set_prio('Helm of the Grave', '', 'Filler', '')
	set_prio('Broken Promise', 'Msg UH? > Tobs UH? > OS/DE', 'Tank stuff', 'Hawkey, Fig')
	set_prio('Final Voyage', 'Inkies?', 'Hunters if they want, then melee', 'Verge')
	set_prio('Gloves of Peaceful Death', 'OS/DE', '', '')
	set_prio('Leggings of Voracious Shadows', 'OS/DE', '', 'Thor, Cluelust')
	set_prio('Urn of Lost Memories', 'Ethos > OS/DE', '', '')
	set_prio('Mantle of the Corrupted', 'DE', '', '')
	set_prio('Damnation', 'OS/DE', '', 'Jules')
	set_prio('Armageddon', '', 'fillter', 'Koro, Greetings')
	set_prio('Breastplate of Frozen Pain', '', 'Filler', 'Sterile, Sandra')
	set_prio('Boots of the Great Construct', 'OS/DE', 'BIS Enh?', 'Died')
	set_prio('Gloves of Fast Reactions', 'Sell', 'BoE', 'Coonixx')
	set_prio('Platehelm of the Great Wyrm', 'DE', 'No meta', '')
	set_prio('Heroic Key to the Focusing Iris', '',
		'Prot Pally > Demo > Dps Warrior = Aff = Ele >= Hunter = Enhance = Ret = Shadow = Boomy = Fire = Arcane > Unholy DK > Frost DK > Hpal > Hpriest = Disc > Rsham > Prot Warrior > Rdruid = Bear = Blood DK'
		, 'Fig, Thor, Trisp, Pili, Chriski, Zlops, Sweet Azz, cy, Aaron')
	set_prio('Icy Blast Amulet', 'Hunter', '2nd BIS for Rogues', 'Inkies, Verge')
	set_prio('Key to the Focusing Iris', '', '10 man key to keep track',
		'Squirties, Beanpole, Coonixx, Heasy, Died, Cypack, Aaron, Zeforr, Inkies, Hellgrazer')
	set_prio('Murder', 'OS/DE', 'Rogue / Hunter filler?', 'Verge')
	set_prio('Gatekeeper', 'Hawkey > OS/DE', 'fig>hawkey bis', 'Fig, Trisp')
	set_prio('Bandit\'s Insignia', 'OS/DE', 'dogshit', '')
	set_prio('Rune of Repulsion', '', 'avoidance set maybe, weird item', 'Hawkeydk')
	set_prio('Sympathy', '', 'Filler', '')
	set_prio('Gloves of Grandeur', '', '', '')
	set_prio('Bone-Inlaid Legguards', 'OS/DE', 'meh', '')
	set_prio('Legguards of the Boneyard', '', '', '')
	set_prio('Legwraps of the Defeated Dragon', 'RFI/DE', 'Filler', 'Shazz, Cypack')
	set_prio('Ceaseless Pity', 'DE', '', '')
	set_prio('Cosmic Lights', '', 'Filler', '')
	set_prio('Ring of Decaying Beauty', 'RFI/DE', '', 'Cluelust, Jess')
	set_prio('Noble Birthright Pauldrons', 'RFI', 'Hpals run tier instead', '')
	set_prio('Extract of Necromantic Power', 'OS/DE', 'BiS: Spriest', 'Zeforr, Zlips')
	set_prio('Soul of the Dead', 'Maybe Hpal? > OS/DE', 'Maybe BiS: RSham, HPal', 'Cluelust')
	set_prio('Drape of the Deadly Foe', 'Bean', 'BiS: Rogue, Hunter, Frost, Unholy, Ret, Feral', 'Verge, Msg')
	set_prio('Calamity\'s Grasp', 'Died > Rogues', 'BiS: Combat and Enh', '')
	set_prio('Boundless Ambition', 'Fig > Trisp OS', 'BiS: Blood and Prot (Armor)', 'Hawkey, Hovden OS')
	set_prio('Wall of Terror', 'OS/DE', 'BiS: Prot', 'Fig, Trisp, Jess, Sterile')
	set_prio('Last Laugh', '', 'BiS: Prot > Unh > Blood', 'Fig, Msg')
	set_prio('Sinister Revenge', 'Hunters', 'BIS Assassin Rogue & Hunter DW', 'Inkies, Verge, Elguapo')
	set_prio('Envoy of Mortality', 'Bean > Elguapo > Trisp > Rogues',
		'BiS: Hunter and Rogue - consider pili for dwarf gun prio', 'Pili')
	set_prio('Betrayer of Humanity', 'Trisp (fury) > Hunter?', 'BiS: Arms, Ret, Unholy, Blood?', 'Trisp, Pili')
	set_prio('Journey\'s End', '', 'BiS: Feral/Hunter - Both have 25m Heigen', 'Coonixx')
	set_prio('Cape of the Unworthy Wizard', '', 'BiS: Disc/Demo', 'Ethos')
	set_prio('Leggings of Mortal Arrogance', 'RFI/DE', 'BiS: Disc/Demo', 'Ethos, Aaron, Zlips, Zeforr')
	set_prio('The Turning Tide', 'Jules', 'BiS HPal weapon after a long line of casters', 'Aaron')
	set_prio('Torch of Holy Fire', 'Thor', 'BiS: Disc, RDruid, RSham, Ele, Spriest', 'Jess')
	set_prio('Voice of Reason', 'Thor > Sterile > Cluelust > Jess', 'BiS: Ele, RSham and HPal', '')
	set_prio('Signet of Manifested Pain', 'Samme', 'BiS: Literally every SP user, reward pumpers (possibly enh bis too)',
		'Heasy')
	set_prio('Crown of the Lost Conqueror', 'RFI MS > OS', 'Prot > Demo > Aff > Ret',
		'Fig, Aaron, Cypack, Azz, Sandra, Sterile OS')
	set_prio('Crown of the Lost Protector', 'Hunter filler?', 'Ele > Arms > Resto', 'Thor, Trisp, Cluelust')
	set_prio('Crown of the Lost Vanquisher', 'Hov > Mages (ask Aaron)', '', 'Chris, Hawkey, Inkies, Verge, Coonixx')
	set_prio('Hyaline Helm of the Sniper', '', 'Filler', '')
	set_prio('Dragon Brood Legguards', '', 'Filler', 'Trisp')
	set_prio('Concealment Shoulderpads', 'RFI/DE', 'Filler', 'Coonixx, Verge')
	set_prio('Fury of the Five Flights', 'Beanpole > Inkies/Verge/Msg BiS if no DMC', 'BiS: Ret, Trap-weave Hunter',
		'Sandra, Pili, Elguapo')
	set_prio('Chestplate of the Great Aspects', 'OS/DE', 'Filler', '')
	set_prio('Wyrmrest Band', 'Saicere > RFI/OS', 'BiS: Disc, top 4 option for the other healers',
		'Sterile, Ethos, Cluelust')
	set_prio('Council Chamber Epaulets', 'OS/DE', 'Filler', '')
	set_prio('Mantle of the Eternal Sentinel', 'Sell',
		'BoE, good for Ele if they dont need hit, filler for HPal/RSham/Balance', '')
	set_prio('Illustration of the Dragon Soul', 'Zef > Who Pumps?', 'yell at ethos if this buff ever drops', 'Ethos')
	set_prio('Staff of Restraint', 'OS/DE', 'Filler, Everyone wants 1h+oh over staves', '')
	set_prio('Gauntlets of the Lost Conqueror', 'Hpals > Spriests', 'fig > demo > hpal > spriest > ret = aff > disc',
		'Fig, Icantwalk, Shazz, Aaron, Cypack')
	set_prio('Gauntlets of the Lost Protector', '', 'Enh > ??', 'Died, Trisp, Thor, Died, Elguapo, Died OS')
	set_prio('Gauntlets of the Lost Vanquisher', 'Mages', 'Balance > Blood DK > Frost DK > Arcane', 'Chris, Greetings, Tobs')
	set_prio('Dragonstorm Breastplate', 'OS/DE', 'Blood?', 'Greetings, Trisp OS')
	set_prio('Upstanding Spaulders', 'RFI', 'Filler', '')
	set_prio('The Sanctum\'s Flowing Vestments', 'Samme', 'BiS: Spriest, Arcane', 'Zeforr, Jules, heasy')
	set_prio('Bountiful Gauntlets', 'RFI', 'Filler', 'Cluelust, Thor')
	set_prio('Obsidian Greathelm', 'Tobs > Trisp? > koro', 'BiS: Unholy and Frost/fury', 'Greetings, Msg')
	set_prio('Leggings of the Honored', 'Rogues?', 'BiS: Feral, and an option for Rogue/Ret', 'Hov, Coon, dof')
	set_prio('Pennant Cloak', '',
		'Highest ilvl cloak this phase + only one with a socket, bis for basically every SP user, reward pumpers', 'Zeforr')
	set_prio('Headpiece of Reconciliation', '', 'BiS: RDruid', 'Chris')
	set_prio('Unsullied Cuffs', '', 'BiS: Disc, Spriest, Arcane, Demo, Aff, Balance, RDruid', 'Jules, Samme')
	set_prio('Reins of the Twilight Drake', '', '', '')
	set_prio('Chestguard of the Recluse', 'Verge > Coonixx > Trisp', 'BiS: Cat, Rogue, Arms, Fury', 'Inkies, Hovden')
	set_prio('Boots of Renewed Flight', 'Beanpole', 'BIS: Hunter', 'Pili, Elguapo')
	set_prio('Melancholy Sabatons', 'Tobs', 'BiS: Arms / Frost / Unholy / Ret', 'Trisp, Greetings, Msg, Koro')
	set_prio('Frosted Adroit Handguards', 'Hovden', 'BiS: Rogue, Cat, Ret, Arms, Hunter',
		'Pili, Beanpole, Elguapo, Big Coon')
	set_prio('Blue Aspect Helm', 'Beanpole > Elguapo',
		'BiS: Enh/Hunters - reward the biggest pumper! Who will win? Bean or Died? died imo', 'Died, Pili')
	set_prio('Legplates of Sovereignty', 'OS/DE', 'BiS: Blood and Prot', 'Fig, Hawkey, Trisp OS')
	set_prio('Mark of Norgannon', 'OS/DE', '', '')
	set_prio('Blanketing Robes of Snow', 'OS/DE', 'BiS: Disc', 'Ethos, Zeforr')
	set_prio('Tunic of the Artifact Guardian', 'OS/DE', 'Check what mindblown is using, 4pc + off chest or 4pc + off gloves'
		, 'Cluelust')
	set_prio('Arcanic Tramplers', '', 'BiS: Disc, Spriest, Arcane, Demo, Aff, Balance, RDruid', 'Azz, Zeforr, Zlips')
	set_prio('Boots of Healing Energies', 'RFI/DE', '', 'Saicere, Sterile')
	set_prio('Winter Spectacle Gloves', 'RFI', 'BiS RSham non-tier gloves', 'Cluelust')
	set_prio('Hood of Rationality', 'RFI', 'BiS Disc, Spriest (and Fire)', 'Zeforr, Ethos, Zlips')
	set_prio('Leggings of the Wanton Spellcaster', '', 'BiS for every caster dps except maybe Arcane', '')
	set_prio('Elevated Lair Pauldrons', 'RFI > OS', 'Filler', 'Fig')
	set_prio('Mantle of Dissemination', 'Zeforr > RFI', 'Bis shadow', 'Zlips')
	set_prio('Spaulders of Catatonia', 'Chris want? > OS', 'Filler', '')
	set_prio('Living Ice Crystals', 'Sterile > PVP RFI', 'A bit shit', '')
	set_prio('Leash of Heedless Magic', '', 'BiS Disc, Spriest, Arcane, Balance, RDruid', 'Jules')
	set_prio('Unravelling Strands of Sanity', 'OS/DE', 'BiS: Resto Druid', 'Chris')
	set_prio('Reins of the Azure Drake', 'Tobs for making this sick addon', 'Frost DK BiS - because Azure is like Frost.',
		'')

end
