--[[

Generate loot priorities for phase 1 items.

Usage:
FilthyPrio.SetPrio('ITEM NAME', 'ITEM PRIORITY', 'ITEM NOTES', 'WHO HAS ITEM ALREADY')

Example:
FilthyPrio.SetPrio('Thunderfury, Blessed Blade of the Windseeker', 'Best Tank > Worst Tank', 'Did someone say...?', '')

This will put the following on the 'Thunderfury, Blessed Blade of the Windseeker' item tooltip.

Loot Prio: Best Tank > Worst Tank
Notes: Did someone say...?

The 'Has Item' part will not display because it is blank.

]] --

-- variable for default loot priority string
-- change this if you want it to be something other than MS>OS>DE
FilthyPrio.defaultPrio = "MS>OS>DE"

function FilthyPrio.buildPrio()

    FilthyPrio.SetPrio('Thunderfury, Blessed Blade of the Windseeker', 'Best Tank > Worst Tank', 'Did someone say...?',
        '')
    FilthyPrio.SetPrio('Cloak of Averted Crisis', '', '', '')
    FilthyPrio.SetPrio('Shawl of the Old Maid', '', '', '')
    FilthyPrio.SetPrio('Shroud of Luminosity', '', '', '')
    FilthyPrio.SetPrio('Cloak of the Shadowed Sun', '', '', '')
    FilthyPrio.SetPrio('Thunderstorm Amulet', '', '', '')
    FilthyPrio.SetPrio('Lost Jewel', '', '', '')
    FilthyPrio.SetPrio('Seized Beauty', '', '', '')
    FilthyPrio.SetPrio('Dying Curse', '', '', '')
    FilthyPrio.SetPrio('Forethought Talisman', '', '', '')
    FilthyPrio.SetPrio('Heritage', '', '', '')
    FilthyPrio.SetPrio('Fool\'s Trial', '', '', '')
    FilthyPrio.SetPrio('Sand-Worn Band', '', '', '')
    FilthyPrio.SetPrio('Ruthlessness', '', '', '')
    FilthyPrio.SetPrio('Strong-Handed Ring', '', '', '')
    FilthyPrio.SetPrio('Defender\'s Code', '', '', '')
    FilthyPrio.SetPrio('Grim Toll', '', '', '')
    FilthyPrio.SetPrio('Shadow of the Ghoul', '', '', '')
    FilthyPrio.SetPrio('Boots of the Escaped Captive', '', '', '')
    FilthyPrio.SetPrio('Ousted Bead Necklace', '', '', '')
    FilthyPrio.SetPrio('Haunting Call', '', '', '')
    FilthyPrio.SetPrio('Silent Crusader', '', '', '')
    FilthyPrio.SetPrio('Shoulderpads of the Undaunted', '', '', '')
    FilthyPrio.SetPrio('Inevitable Defeat', '', '', '')
    FilthyPrio.SetPrio('Corpse Scarab Handguards', '', '', '')
    FilthyPrio.SetPrio('Rescinding Grips', '', '', '')
    FilthyPrio.SetPrio('Leggings of Atrophy', '', '', '')
    FilthyPrio.SetPrio('Chains of Adoration', '', '', '')
    FilthyPrio.SetPrio('Shield of Assimilation', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Locusts', '', '', '')
    FilthyPrio.SetPrio('Sash of the Parlor', '', '', '')
    FilthyPrio.SetPrio('Gemmed Wand of the Nerubians', '', '', '')
    FilthyPrio.SetPrio('Swarm Bindings', '', '', '')
    FilthyPrio.SetPrio('Dawnwalkers', '', '', '')
    FilthyPrio.SetPrio('Inexorable Sabatons', '', '', '')
    FilthyPrio.SetPrio('Sabatons of Sudden Revival', '', '', '')
    FilthyPrio.SetPrio('Webbed Death', '', '', '')
    FilthyPrio.SetPrio('Pauldrons of Unnatural Death', '', '', '')
    FilthyPrio.SetPrio('Arachnoid Gold Band', '', '', '')
    FilthyPrio.SetPrio('Cult\'s Chestguard', '', '', '')
    FilthyPrio.SetPrio('Tunic of Prejudice', '', '', '')
    FilthyPrio.SetPrio('Atonement Greaves', '', '', '')
    FilthyPrio.SetPrio('Gloves of Token Respect', '', '', '')
    FilthyPrio.SetPrio('Faerlina\'s Madness', '', '', '')
    FilthyPrio.SetPrio('Epaulets of the Grieving Servant', '', '', '')
    FilthyPrio.SetPrio('Belt of False Dignity', '', '', '')
    FilthyPrio.SetPrio('Totem of Misery', '', '', '')
    FilthyPrio.SetPrio('Punctilious Bindings', '', '', '')
    FilthyPrio.SetPrio('Dislocating Handguards', '', '', '')
    FilthyPrio.SetPrio('Callous-Hearted Gauntlets', '', '', '')
    FilthyPrio.SetPrio('Fire-Scorched Greathelm', '', '', '')
    FilthyPrio.SetPrio('Widow\'s Fury', 'Msg?', '', '', '')
    FilthyPrio.SetPrio('Idol of Worship', '', '', '')
    FilthyPrio.SetPrio('Bracers of the Tyrant', '', '', '')
    FilthyPrio.SetPrio('Aged Winter Cloak', '', '', '')
    FilthyPrio.SetPrio('Undiminished Battleplate', '', '', '')
    FilthyPrio.SetPrio('Digested Silken Robes', '', '', '')
    FilthyPrio.SetPrio('Quivering Tunic', '', '', '')
    FilthyPrio.SetPrio('Cowl of the Perished', '', '', '')
    FilthyPrio.SetPrio('Helm of Diminished Pride', '', '', '')
    FilthyPrio.SetPrio('Distorted Limbs', '', '', '')
    FilthyPrio.SetPrio('Wraith Strike', '', '', '')
    FilthyPrio.SetPrio('Matriarch\'s Spawn', '', '', '')
    FilthyPrio.SetPrio('Mantle of Scattered Kinship', '', '', '')
    FilthyPrio.SetPrio('Infectious Skitterer Leggings', '', '', '')
    FilthyPrio.SetPrio('The Jawbone', '', '', '')
    FilthyPrio.SetPrio('Torn Web Wrapping', '', '', '')
    FilthyPrio.SetPrio('Ablative Chitin Girdle', '', '', '')
    FilthyPrio.SetPrio('Sinner\'s Bindings', '', '', '')
    FilthyPrio.SetPrio('Bindings of the Hapless Prey', '', '', '')
    FilthyPrio.SetPrio('Gloves of Calculated Risk', '', '', '')
    FilthyPrio.SetPrio('Crude Discolored Battlegrips', '', '', '')
    FilthyPrio.SetPrio('Boots of Septic Wounds', '', '', '')
    FilthyPrio.SetPrio('Boots of Persuasion', '', '', '')
    FilthyPrio.SetPrio('Surplus Limb', '', '', '')
    FilthyPrio.SetPrio('Waistguard of Divine Grace', '', '', '')
    FilthyPrio.SetPrio('Libram of Tolerance', '', '', '')
    FilthyPrio.SetPrio('Girdle of the Gambit', '', '', '')
    FilthyPrio.SetPrio('Sash of Solitude', '', '', '')
    FilthyPrio.SetPrio('Totem of Hex', '', '', '')
    FilthyPrio.SetPrio('Hero\'s Surrender', '', '', '')
    FilthyPrio.SetPrio('Split Greathammer', '', '', '')
    FilthyPrio.SetPrio('Arrowsong', '', '', '')
    FilthyPrio.SetPrio('Belt of the Tortured', '', '', '')
    FilthyPrio.SetPrio('Fleshless Girdle', '', '', '')
    FilthyPrio.SetPrio('Tunic of Indulgence', '', '', '')
    FilthyPrio.SetPrio('Chestguard of the Exhausted', '', '', '')
    FilthyPrio.SetPrio('Fallout Impervious Tunic', '', '', '')
    FilthyPrio.SetPrio('Cowl of Vanity', '', '', '')
    FilthyPrio.SetPrio('Desecrated Past', '', '', '')
    FilthyPrio.SetPrio('Plague Igniter', '', '', '')
    FilthyPrio.SetPrio('Sympathetic Amice', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Fatigued Sage', '', '', '')
    FilthyPrio.SetPrio('Spaulders of Incoherence', '', '', '')
    FilthyPrio.SetPrio('Bracers of Liberation', '', '', '')
    FilthyPrio.SetPrio('Twilight Mist', '', '', '')
    FilthyPrio.SetPrio('Origin of Nightmares', '', '', '')
    FilthyPrio.SetPrio('Depraved Linked Belt', '', '', '')
    FilthyPrio.SetPrio('Girdle of Chivalry', '', '', '')
    FilthyPrio.SetPrio('Slime Stream Bands', '', '', '')
    FilthyPrio.SetPrio('Sabatons of Endurance', '', '', '')
    FilthyPrio.SetPrio('Cover of Silence', '', '', '')
    FilthyPrio.SetPrio('Riveted Abomination Leggings', '', '', '')
    FilthyPrio.SetPrio('Benefactor\'s Gauntlets', '', '', '')
    FilthyPrio.SetPrio('Wraps of the Persecuted', '', '', '')
    FilthyPrio.SetPrio('Faceguard of the Succumbed', '', '', '')
    FilthyPrio.SetPrio('Headpiece of Fungal Bloom', '', '', '')
    FilthyPrio.SetPrio('Pauldrons of the Abandoned', '', '', '')
    FilthyPrio.SetPrio('Spire of Sunset', '', '', '')
    FilthyPrio.SetPrio('Cincture of Polarity', '', '', '')
    FilthyPrio.SetPrio('Legplates of the Lost Conqueror', '', '', '')
    FilthyPrio.SetPrio('Legplates of the Lost Protector', '', '', '')
    FilthyPrio.SetPrio('Legplates of the Lost Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Tunic of Masked Suffering', '', '', '')
    FilthyPrio.SetPrio('Crippled Treads', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of the Disobedient', '', '', '')
    FilthyPrio.SetPrio('Robes of Mutation', '', '', '')
    FilthyPrio.SetPrio('Poignant Sabatons', '', '', '')
    FilthyPrio.SetPrio('Gloves of the Fallen Wizard', '', '', '')
    FilthyPrio.SetPrio('Legguards of the Undisturbed', '', '', '')
    FilthyPrio.SetPrio('Accursed Spine', '', '', '')
    FilthyPrio.SetPrio('Belt of Potent Chanting', '', '', '')
    FilthyPrio.SetPrio('Bands of Impurity', '', '', '')
    FilthyPrio.SetPrio('Libram of Radiance', '', '', '')
    FilthyPrio.SetPrio('Angry Dread', '', '', '')
    FilthyPrio.SetPrio('Shoulderguards of Opportunity', '', '', '')
    FilthyPrio.SetPrio('Spinning Fate', '', '', '')
    FilthyPrio.SetPrio('Thrusting Bands', '', '', '')
    FilthyPrio.SetPrio('Breastplate of Tormented Rage', '', '', '')
    FilthyPrio.SetPrio('Iron-Spring Jumpers', '', '', '')
    FilthyPrio.SetPrio('Leggings of Colossal Strides', '', '', '')
    FilthyPrio.SetPrio('Eruption-Scarred Boots', '', '', '')
    FilthyPrio.SetPrio('Chestguard of Bitter Charms', '', '', '')
    FilthyPrio.SetPrio('Heigan\'s Putrid Vestments', '', '', '')
    FilthyPrio.SetPrio('Serene Echoes', '', '', '')
    FilthyPrio.SetPrio('Gloves of the Dancing Bear', '', '', '')
    FilthyPrio.SetPrio('Helm of Pilgrimage', '', '', '')
    FilthyPrio.SetPrio('Legguards of the Apostle', '', '', '')
    FilthyPrio.SetPrio('Bindings of the Decrepit', '', '', '')
    FilthyPrio.SetPrio('Sigil of Awareness', '', '', '')
    FilthyPrio.SetPrio('Cryptfiend\'s Bite', '', '', '')
    FilthyPrio.SetPrio('The Undeath Carrier', '', '', '')
    FilthyPrio.SetPrio('Stalk-Skin Belt', '', '', '')
    FilthyPrio.SetPrio('Footwraps of Vile Deceit', '', '', '')
    FilthyPrio.SetPrio('Grotesque Handgrips', '', '', '')
    FilthyPrio.SetPrio('Greaves of Turbulence', '', '', '')
    FilthyPrio.SetPrio('The Hand of Nerub', '', '', '')
    FilthyPrio.SetPrio('Vest of Vitality', '', '', '')
    FilthyPrio.SetPrio('Boots of Impetuous Ideals', '', '', '')
    FilthyPrio.SetPrio('Cowl of Innocent Delight', '', '', '')
    FilthyPrio.SetPrio('The Impossible Dream', '', '', '')
    FilthyPrio.SetPrio('Girdle of Unity', '', '', '')
    FilthyPrio.SetPrio('Fading Glow', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Lost Conqueror', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Lost Protector', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Lost Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Chestpiece of Suspicion', '', '', '')
    FilthyPrio.SetPrio('Legplates of Double Strikes', '', '', '')
    FilthyPrio.SetPrio('Boots of Forlorn Wishes', '', '', '')
    FilthyPrio.SetPrio('Faithful Steel Sabatons', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of Guiding Touch', '', '', '')
    FilthyPrio.SetPrio('Girdle of Recuperation', '', '', '')
    FilthyPrio.SetPrio('Bands of Mutual Respect', '', '', '')
    FilthyPrio.SetPrio('Bindings of the Expansive Mind', '', '', '')
    FilthyPrio.SetPrio('Esteemed Bindings', '', '', '')
    FilthyPrio.SetPrio('Idol of the Shooting Star', '', '', '')
    FilthyPrio.SetPrio('Spaulders of Egotism', '', '', '')
    FilthyPrio.SetPrio('Shoulderpads of Secret Arts', '', '', '')
    FilthyPrio.SetPrio('Totem of Dueling', '', '', '')
    FilthyPrio.SetPrio('Girdle of Razuvious', '', '', '')
    FilthyPrio.SetPrio('Bracers of the Unholy Knight', '', '', '')
    FilthyPrio.SetPrio('Hood of the Exodus', '', '', '')
    FilthyPrio.SetPrio('Helm of Vital Protection', '', '', '')
    FilthyPrio.SetPrio('Leggings of Fleeting Moments', '', '', '')
    FilthyPrio.SetPrio('Leggings of Failed Escape', '', '', '')
    FilthyPrio.SetPrio('Libram of Resurgence', '', '', '')
    FilthyPrio.SetPrio('Gothik\'s Cowl', '', '', '')
    FilthyPrio.SetPrio('Helm of Unleashed Energy', '', '', '')
    FilthyPrio.SetPrio('Life and Death', '', '', '')
    FilthyPrio.SetPrio('Shackled Cinch', '', '', '')
    FilthyPrio.SetPrio('Idol of Awakening', '', '', '')
    FilthyPrio.SetPrio('Touch of Horror', '', '', '')
    FilthyPrio.SetPrio('Abetment Bracers', '', '', '')
    FilthyPrio.SetPrio('Bindings of Yearning', '', '', '')
    FilthyPrio.SetPrio('Burdened Shoulderplates', '', '', '')
    FilthyPrio.SetPrio('Bracers of Unrelenting Attack', '', '', '')
    FilthyPrio.SetPrio('Breastplate of the Lost Conqueror', '', '', '')
    FilthyPrio.SetPrio('Breastplate of the Lost Protector', '', '', '')
    FilthyPrio.SetPrio('Breastplate of the Lost Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Zeliek\'s Gauntlets', '', '', '')
    FilthyPrio.SetPrio('Helm of the Grave', '', '', '')
    FilthyPrio.SetPrio('Broken Promise', '', '', '')
    FilthyPrio.SetPrio('Final Voyage', '', '', '')
    FilthyPrio.SetPrio('Gloves of Peaceful Death', '', '', '')
    FilthyPrio.SetPrio('Leggings of Voracious Shadows', '', '', '')
    FilthyPrio.SetPrio('Urn of Lost Memories', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Corrupted', '', '', '')
    FilthyPrio.SetPrio('Damnation', '', '', '')
    FilthyPrio.SetPrio('Armageddon', '', '', '')
    FilthyPrio.SetPrio('Breastplate of Frozen Pain', '', '', '')
    FilthyPrio.SetPrio('Boots of the Great Construct', '', '', '')
    FilthyPrio.SetPrio('Gloves of Fast Reactions', '', '', '')
    FilthyPrio.SetPrio('Platehelm of the Great Wyrm', '', '', '')
    FilthyPrio.SetPrio('Heroic Key to the Focusing Iris', '',
        'Prot Pally > Demo > Dps Warrior = Aff = Ele >= Hunter = Enhance = Ret = Shadow = Boomy = Fire = Arcane > Hpal > Hpriest = Disc > Rsham > Frost/Unholy DK = Rogue > Prot Warrior > Rdruid = Bear = Blood DK'
        , '')
    FilthyPrio.SetPrio('Icy Blast Amulet', '', '', '')
    FilthyPrio.SetPrio('Key to the Focusing Iris', '', '', '')
    FilthyPrio.SetPrio('Murder', '', '', '')
    FilthyPrio.SetPrio('Gatekeeper', '', '', '')
    FilthyPrio.SetPrio('Bandit\'s Insignia', '', '', '')
    FilthyPrio.SetPrio('Rune of Repulsion', '', '', '')
    FilthyPrio.SetPrio('Sympathy', '', '', '')
    FilthyPrio.SetPrio('Gloves of Grandeur', '', '', '')
    FilthyPrio.SetPrio('Bone-Inlaid Legguards', '', '', '')
    FilthyPrio.SetPrio('Legguards of the Boneyard', '', '', '')
    FilthyPrio.SetPrio('Legwraps of the Defeated Dragon', '', '', '')
    FilthyPrio.SetPrio('Ceaseless Pity', '', '', '')
    FilthyPrio.SetPrio('Cosmic Lights', '', '', '')
    FilthyPrio.SetPrio('Ring of Decaying Beauty', '', '', '')
    FilthyPrio.SetPrio('Noble Birthright Pauldrons', '', '', '')
    FilthyPrio.SetPrio('Extract of Necromantic Power', '', '', '')
    FilthyPrio.SetPrio('Soul of the Dead', '', '', '')
    FilthyPrio.SetPrio('Drape of the Deadly Foe', '', '', '')
    FilthyPrio.SetPrio('Calamity\'s Grasp', '', '', '')
    FilthyPrio.SetPrio('Boundless Ambition', '', '', '')
    FilthyPrio.SetPrio('Wall of Terror', '', '', '')
    FilthyPrio.SetPrio('Last Laugh', '', '', '')
    FilthyPrio.SetPrio('Sinister Revenge', '', '', '')
    FilthyPrio.SetPrio('Envoy of Mortality', '', '', '')
    FilthyPrio.SetPrio('Betrayer of Humanity', '', '', '')
    FilthyPrio.SetPrio('Journey\'s End', '', '', '')
    FilthyPrio.SetPrio('Cape of the Unworthy Wizard', '', '', '')
    FilthyPrio.SetPrio('Leggings of Mortal Arrogance', '', '', '')
    FilthyPrio.SetPrio('The Turning Tide', '', '', '')
    FilthyPrio.SetPrio('Torch of Holy Fire', '', '', '')
    FilthyPrio.SetPrio('Voice of Reason', '', '', '')
    FilthyPrio.SetPrio('Signet of Manifested Pain', '', '', '')
    FilthyPrio.SetPrio('Crown of the Lost Conqueror', '', '', '')
    FilthyPrio.SetPrio('Crown of the Lost Protector', '', '', '')
    FilthyPrio.SetPrio('Crown of the Lost Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Hyaline Helm of the Sniper', '', '', '')
    FilthyPrio.SetPrio('Dragon Brood Legguards', '', '', '')
    FilthyPrio.SetPrio('Concealment Shoulderpads', '', '', '')
    FilthyPrio.SetPrio('Fury of the Five Flights', '', '', '')
    FilthyPrio.SetPrio('Chestplate of the Great Aspects', '', '', '')
    FilthyPrio.SetPrio('Wyrmrest Band', '', '', '')
    FilthyPrio.SetPrio('Council Chamber Epaulets', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Eternal Sentinel', '', '', '')
    FilthyPrio.SetPrio('Illustration of the Dragon Soul', '', '', '')
    FilthyPrio.SetPrio('Staff of Restraint', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of the Lost Conqueror', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of the Lost Protector', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of the Lost Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Dragonstorm Breastplate', '', '', '')
    FilthyPrio.SetPrio('Upstanding Spaulders', '', '', '')
    FilthyPrio.SetPrio('The Sanctum\'s Flowing Vestments', '', '', '')
    FilthyPrio.SetPrio('Bountiful Gauntlets', '', '', '')
    FilthyPrio.SetPrio('Obsidian Greathelm', '', '', '')
    FilthyPrio.SetPrio('Leggings of the Honored', '', '', '')
    FilthyPrio.SetPrio('Pennant Cloak', '', '', '')
    FilthyPrio.SetPrio('Headpiece of Reconciliation', '', '', '')
    FilthyPrio.SetPrio('Unsullied Cuffs', '', '', '')
    FilthyPrio.SetPrio('Reins of the Twilight Drake', '', '', '')
    FilthyPrio.SetPrio('Chestguard of the Recluse', '', '', '')
    FilthyPrio.SetPrio('Boots of Renewed Flight', '', '', '')
    FilthyPrio.SetPrio('Melancholy Sabatons', '', '', '')
    FilthyPrio.SetPrio('Frosted Adroit Handguards', '', '', '')
    FilthyPrio.SetPrio('Blue Aspect Helm', '', '', '')
    FilthyPrio.SetPrio('Legplates of Sovereignty', '', '', '')
    FilthyPrio.SetPrio('Mark of Norgannon', '', '', '')
    FilthyPrio.SetPrio('Blanketing Robes of Snow', '', '', '')
    FilthyPrio.SetPrio('Tunic of the Artifact Guardian', '', '', '')
    FilthyPrio.SetPrio('Arcanic Tramplers', '', '', '')
    FilthyPrio.SetPrio('Boots of Healing Energies', '', '', '')
    FilthyPrio.SetPrio('Winter Spectacle Gloves', '', '', '')
    FilthyPrio.SetPrio('Hood of Rationality', '', '', '')
    FilthyPrio.SetPrio('Leggings of the Wanton Spellcaster', '', '', '')
    FilthyPrio.SetPrio('Elevated Lair Pauldrons', '', '', '')
    FilthyPrio.SetPrio('Mantle of Dissemination', '', '', '')
    FilthyPrio.SetPrio('Spaulders of Catatonia', '', '', '')
    FilthyPrio.SetPrio('Living Ice Crystals', '', '', '')
    FilthyPrio.SetPrio('Leash of Heedless Magic', '', '', '')
    FilthyPrio.SetPrio('Unravelling Strands of Sanity', '', '', '')
    FilthyPrio.SetPrio('Reins of the Azure Drake', '', '', '')

end
