--[[

Generate loot priorities for phase 1 items.

Usage:
FilthyPrio.SetPrio('ITEM NAME', 'ITEM PRIORITY', 'ITEM NOTES', 'WHO HAS ITEM ALREADY')

Example:
FilthyPrio.SetPrio('Thunderfury, Blessed Blade of the Windseeker', 'Best Tank > Worst Tank', 'Did someone say...?', '')

This will put the following on the 'Thunderfury, Blessed Blade of the Windseeker' item tooltip.

Loot Prio: Best Tank > Worst Tank
Notes: Did someone say...?

The 'Has Item' part will not display because it is blank.

]] --

-- variable for default loot priority string
-- change this if you want it to be something other than MS>OS>DE
FilthyPrio.defaultPrio = "MS>OS>DE"

function FilthyPrio.buildPrioP2()
    FilthyPrio.SetPrio('Band of Lights', '', '', '')
    FilthyPrio.SetPrio('Breastplate of the Timeless', '', '', '')
    FilthyPrio.SetPrio('Dark Matter', '', '', '')
    FilthyPrio.SetPrio('Drape of the Messenger', '', '', '')
    FilthyPrio.SetPrio('Gloves of the Endless Dark', '', '', '')
    FilthyPrio.SetPrio('Meteorite Crystal', '', '', '')
    FilthyPrio.SetPrio('Nebula Band', '', '', '')
    FilthyPrio.SetPrio('Observer\'s Mantle', '', '', '')
    FilthyPrio.SetPrio('Pendant of the Somber Witness', '', '', '')
    FilthyPrio.SetPrio('Pulsar Gloves', '', '', '')
    FilthyPrio.SetPrio('Reply-Code Alpha', '', '', '')
    FilthyPrio.SetPrio('Shoulderplates of the Celestial Watch', '', '', '')
    FilthyPrio.SetPrio('Starfall Girdle', '', '', '')
    FilthyPrio.SetPrio('Starlight Treads', '', '', '')
    FilthyPrio.SetPrio('Strength of the Heavens', '', '', '')
    FilthyPrio.SetPrio('Zodiac Leggings', '', '', '')
    FilthyPrio.SetPrio('Boundless Gaze', '', '', '')
    FilthyPrio.SetPrio('Bulwark of Algalon', '', '', '')
    FilthyPrio.SetPrio('Comet\'s Trail', '', '', '')
    FilthyPrio.SetPrio('Constellus', '', '', '')
    FilthyPrio.SetPrio('Cosmos', '', '', '')
    FilthyPrio.SetPrio('Legplates of the Endless Void', '', '', '')
    FilthyPrio.SetPrio('Pharos Gloves', '', '', '')
    FilthyPrio.SetPrio('Planewalker Treads', '', '', '')
    FilthyPrio.SetPrio('Reply-Code Alpha', '', '', '')
    FilthyPrio.SetPrio('Sabatons of Lifeless Night', '', '', '')
    FilthyPrio.SetPrio('Solar Bindings', '', '', '')
    FilthyPrio.SetPrio('Star-beaded Clutch', '', '', '')
    FilthyPrio.SetPrio('Starwatcher\'s Binding', '', '', '')
    FilthyPrio.SetPrio('Fang of Oblivion', '', '', '')
    FilthyPrio.SetPrio('Dreambinder', '', '', '')
    FilthyPrio.SetPrio('Starshard Edge', '', '', '')
    FilthyPrio.SetPrio('Skyforge Crossbow', '', '', '')
    FilthyPrio.SetPrio('Fragment of Val\'anyr', '', '', '')
    FilthyPrio.SetPrio('Archaedas\' Lost Legplates', '', '', '')
    FilthyPrio.SetPrio('Chestplate of Titanic Fury', '', '', '')
    FilthyPrio.SetPrio('Cover of the Keepers', '', '', '')
    FilthyPrio.SetPrio('Elemental Focus Stone', '', '', '')
    FilthyPrio.SetPrio('Ironaya\'s Discarded Mantle', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Preserver', '', '', '')
    FilthyPrio.SetPrio('Nimble Climber\'s Belt', '', '', '')
    FilthyPrio.SetPrio('Nurturing Touch', '', '', '')
    FilthyPrio.SetPrio('Raiments of the Corrupted', '', '', '')
    FilthyPrio.SetPrio('Shieldwall of the Breaker', '', '', '')
    FilthyPrio.SetPrio('Amice of the Stoic Watch', '', '', '')
    FilthyPrio.SetPrio('Cloak of the Makers', '', '', '')
    FilthyPrio.SetPrio('Cowl of the Absolute', '', '', '')
    FilthyPrio.SetPrio('Gloves of the Stonereaper', '', '', '')
    FilthyPrio.SetPrio('Greaves of the Rockmender', '', '', '')
    FilthyPrio.SetPrio('Libram of the Resolute', '', '', '')
    FilthyPrio.SetPrio('Platinum Band of the Aesir', '', '', '')
    FilthyPrio.SetPrio('Ring of the Faithful Servant', '', '', '')
    FilthyPrio.SetPrio('Sandals of the Ancient Keeper', '', '', '')
    FilthyPrio.SetPrio('Shoulderplates of the Eternal', '', '', '')
    FilthyPrio.SetPrio('Unbreakable Chestguard', '', '', '')
    FilthyPrio.SetPrio('Unwavering Stare', '', '', '')
    FilthyPrio.SetPrio('Runescribed Blade', '', '', '')
    FilthyPrio.SetPrio('Siren\'s Cry', '', '', '')
    FilthyPrio.SetPrio('Stonerender', '', '', '')
    FilthyPrio.SetPrio('Belt of the Iron Servant', '', '', '')
    FilthyPrio.SetPrio('Boots of the Petrified Forest', '', '', '')
    FilthyPrio.SetPrio('Circlet of True Sight', '', '', '')
    FilthyPrio.SetPrio('Cloak of the Iron Council', '', '', '')
    FilthyPrio.SetPrio('Greaves of Iron Intensity', '', '', '')
    FilthyPrio.SetPrio('Lady Maye\'s Sapphire Ring', '', '', '')
    FilthyPrio.SetPrio('Leggings of Swift Reflexes', '', '', '')
    FilthyPrio.SetPrio('Rune-Etched Nightblade', '', '', '')
    FilthyPrio.SetPrio('Runetouch Wristwraps', '', '', '')
    FilthyPrio.SetPrio('Stormtip', '', '', '')
    FilthyPrio.SetPrio('Belt of the Crystal Tree', '', '', '')
    FilthyPrio.SetPrio('Loop of the Agile', '', '', '')
    FilthyPrio.SetPrio('Watchful Eye of Fate', '', '', '')
    FilthyPrio.SetPrio('Perilous Bite', '', '', '')
    FilthyPrio.SetPrio('The Masticator', '', '', '')
    FilthyPrio.SetPrio('Ancient Iron Heaume', '', '', '')
    FilthyPrio.SetPrio('Drape of the Lithe', '', '', '')
    FilthyPrio.SetPrio('Handguards of the Enclave', '', '', '')
    FilthyPrio.SetPrio('Insurmountable Fervor', '', '', '')
    FilthyPrio.SetPrio('Iron-studded Mantle', 'brick', '', '')
    FilthyPrio.SetPrio('Overload Legwraps', '', '', '')
    FilthyPrio.SetPrio('Phaelia\'s Vestments of the Sprouting Seed', '', '', '')
    FilthyPrio.SetPrio('Radiant Seal', '', '', '')
    FilthyPrio.SetPrio('Raiments of the Iron Council', '', '', '')
    FilthyPrio.SetPrio('Runed Ironhide Boots', '', '', '')
    FilthyPrio.SetPrio('Runeshaper\'s Gloves', '', '', '')
    FilthyPrio.SetPrio('Steelbreaker\'s Embrace', '', '', '')
    FilthyPrio.SetPrio('Unblinking Eye', '', '', '')
    FilthyPrio.SetPrio('Rapture', '', '', '')
    FilthyPrio.SetPrio('Stormrune Edge', '', '', '')
    FilthyPrio.SetPrio('Belt of Colossal Rage', '', '', '')
    FilthyPrio.SetPrio('Drape of Mortal Downfall', '', '', '')
    FilthyPrio.SetPrio('Greaves of Swift Vengeance', '', '', '')
    FilthyPrio.SetPrio('Sapphire Amulet of Renewal', '', '', '')
    FilthyPrio.SetPrio('Shoulderpads of the Intruder', '', '', '')
    FilthyPrio.SetPrio('Chestguard of the Lasher', '', '', '')
    FilthyPrio.SetPrio('Gloves of the Wayward Conqueror', '', '', '')
    FilthyPrio.SetPrio('Gloves of the Wayward Protector', '', '', '')
    FilthyPrio.SetPrio('Gloves of the Wayward Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Ironbark Faceguard', '', '', '')
    FilthyPrio.SetPrio('Legplates of Flourishing Resolve', '', '', '')
    FilthyPrio.SetPrio('Tunic of the Limber Stalker', '', '', '')
    FilthyPrio.SetPrio('Unraveling Reach', '', '', '')
    FilthyPrio.SetPrio('Fire Orchid Signet', '', '', '')
    FilthyPrio.SetPrio('Gloves of Whispering Winds', '', '', '')
    FilthyPrio.SetPrio('Seed of Budding Carnage', '', '', '')
    FilthyPrio.SetPrio('Petrified Ivy Sprig', '', '', '')
    FilthyPrio.SetPrio('Serilas, Blood Blade of Invar One-Arm', '', '', '')
    FilthyPrio.SetPrio('Boots of the Servant', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of Ruthless Reprisal', '', '', '')
    FilthyPrio.SetPrio('Leggings of the Lifetender', '', '', '')
    FilthyPrio.SetPrio('Legplates of the Wayward Conqueror', '', '', '')
    FilthyPrio.SetPrio('Legplates of the Wayward Protector', '', '', '')
    FilthyPrio.SetPrio('Legplates of the Wayward Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Nymph Heart Charm', '', '', '')
    FilthyPrio.SetPrio('The Lifebinder', '', '', '')
    FilthyPrio.SetPrio('Bladetwister', '', '', '')
    FilthyPrio.SetPrio('Bronze Pendant of the Vanir', '', '', '')
    FilthyPrio.SetPrio('Drape of the Sullen Goddess', '', '', '')
    FilthyPrio.SetPrio('Handguards of Revitalization', '', '', '')
    FilthyPrio.SetPrio('Leggings of the Enslaved Idol', '', '', '')
    FilthyPrio.SetPrio('Avalanche', '', '', '')
    FilthyPrio.SetPrio('Cowl of Icy Breaths', '', '', '')
    FilthyPrio.SetPrio('Leggings of the Wayward Conqueror', '', '', '')
    FilthyPrio.SetPrio('Leggings of the Wayward Protector', '', '', '')
    FilthyPrio.SetPrio('Leggings of the Wayward Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Signet of Winter', '', '', '')
    FilthyPrio.SetPrio('Stormedge', '', '', '')
    FilthyPrio.SetPrio('Winter\'s Frigid Embrace', '', '', '')
    FilthyPrio.SetPrio('Bitter Cold Armguards', '', '', '')
    FilthyPrio.SetPrio('Icecore Staff', '', '', '')
    FilthyPrio.SetPrio('Ice Layered Barrier', '', '', '')
    FilthyPrio.SetPrio('Shiver', '', '', '')
    FilthyPrio.SetPrio('The Boreal Guard', '', '', '')
    FilthyPrio.SetPrio('Breastplate of the Wayward Conqueror', '', '', '')
    FilthyPrio.SetPrio('Breastplate of the Wayward Protector', '', '', '')
    FilthyPrio.SetPrio('Breastplate of the Wayward Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Frost-bound Chain Bracers', 'hunter', '', '')
    FilthyPrio.SetPrio('Frostplate Greaves', '', '', '')
    FilthyPrio.SetPrio('Frozen Loop', '', '', '')
    FilthyPrio.SetPrio('Northern Barrier', '', '', '')
    FilthyPrio.SetPrio('Winter\'s Icy Embrace', '', '', '')
    FilthyPrio.SetPrio('Bindings of Winter Gale', '', '', '')
    FilthyPrio.SetPrio('Constellus', '', '', '')
    FilthyPrio.SetPrio('Drape of Icy Intent', '', '', '')
    FilthyPrio.SetPrio('Frigid Strength of Hodir', '', '', '')
    FilthyPrio.SetPrio('Gloves of the Frozen Glade', '', '', '')
    FilthyPrio.SetPrio('Staff of Endless Winter', '', '', '')
    FilthyPrio.SetPrio('Armbraces of the Vibrant Flame', '', '', '')
    FilthyPrio.SetPrio('Drape of Fuming Anger', '', '', '')
    FilthyPrio.SetPrio('Furnace Stone', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of the Iron Furnace', '', '', '')
    FilthyPrio.SetPrio('Gloves of Smoldering Touch', '', '', '')
    FilthyPrio.SetPrio('Igniter Rod', '', '', '')
    FilthyPrio.SetPrio('Pauldrons of Tempered Will', '', '', '')
    FilthyPrio.SetPrio('Relentless Edge', '', '', '')
    FilthyPrio.SetPrio('Rifle of the Platinum Guard', '', '', '')
    FilthyPrio.SetPrio('Shawl of the Caretaker', '', '', '')
    FilthyPrio.SetPrio('Charred Saronite Greaves', '', '', '')
    FilthyPrio.SetPrio('Cindershard Ring', '', '', '')
    FilthyPrio.SetPrio('Flamestalker Boots', '', '', '')
    FilthyPrio.SetPrio('Flamewrought Cinch', '', '', '')
    FilthyPrio.SetPrio('Girdle of Embers', '', '', '')
    FilthyPrio.SetPrio('Heart of Iron', '', '', '')
    FilthyPrio.SetPrio('Helm of the Furnace Master', '', '', '')
    FilthyPrio.SetPrio('Lifeforge Breastplate', '', '', '')
    FilthyPrio.SetPrio('Pyrelight Circle', '', '', '')
    FilthyPrio.SetPrio('Soot-Covered Mantle', '', '', '')
    FilthyPrio.SetPrio('Totem of the Dancing Flame', '', '', '')
    FilthyPrio.SetPrio('Wristguards of the Firetender', '', '', '')
    FilthyPrio.SetPrio('Intensity', '', '', '')
    FilthyPrio.SetPrio('Scepter of Creation', '', '', '')
    FilthyPrio.SetPrio('Worldcarver', '', '', '')
    FilthyPrio.SetPrio('Emerald Signet Ring', '', '', '')
    FilthyPrio.SetPrio('Greaves of the Earthbinder', '', '', '')
    FilthyPrio.SetPrio('Mark of the Unyielding', '', '', '')
    FilthyPrio.SetPrio('Pendant of the Piercing Glare', '', '', '')
    FilthyPrio.SetPrio('Sabatons of the Iron Watcher', '', '', '')
    FilthyPrio.SetPrio('Shawl of the Shattered Giant', '', '', '')
    FilthyPrio.SetPrio('Shoulderguards of the Solemn Watch', '', '', '')
    FilthyPrio.SetPrio('Spark of Hope', '', '', '')
    FilthyPrio.SetPrio('Spire of Withering Dreams', '', '', '')
    FilthyPrio.SetPrio('Stoneguard', '', '', '')
    FilthyPrio.SetPrio('Bracers of Unleashed Magic', '', '', '')
    FilthyPrio.SetPrio('Gloves of the Pythonic Guardian', '', '', '')
    FilthyPrio.SetPrio('Handwraps of Plentiful Recovery', '', '', '')
    FilthyPrio.SetPrio('Idol of the Crying Wind', '', '', '')
    FilthyPrio.SetPrio('Ironmender', '', '', '')
    FilthyPrio.SetPrio('Leggings of the Stoneweaver', '', '', '')
    FilthyPrio.SetPrio('Necklace of Unerring Mettle', '', '', '')
    FilthyPrio.SetPrio('Robes of the Umbral Brute', '', '', '')
    FilthyPrio.SetPrio('Saronite Plated Legguards', '', '', '')
    FilthyPrio.SetPrio('Shoulderpads of the Monolith', '', '', '')
    FilthyPrio.SetPrio('Unfaltering Armguards', '', '', '')
    FilthyPrio.SetPrio('Wrathstone', '', '', '')
    FilthyPrio.SetPrio('Giant\'s Bane', '', '', '')
    FilthyPrio.SetPrio('Malice', '', '', '')
    FilthyPrio.SetPrio('Decimator\'s Armguards', '', '', '')
    FilthyPrio.SetPrio('Combustion Bracers', '', '', '')
    FilthyPrio.SetPrio('Energy Siphon', '', '', '')
    FilthyPrio.SetPrio('Firesoul', '', '', '')
    FilthyPrio.SetPrio('Firestrider Chestguard', '', '', '')
    FilthyPrio.SetPrio('Flamewatch Armguards', '', '', '')
    FilthyPrio.SetPrio('Ironsoul', '', '', '')
    FilthyPrio.SetPrio('Kinetic Ripper', '', '', '')
    FilthyPrio.SetPrio('Lifespark Visage', '', '', '')
    FilthyPrio.SetPrio('Might of the Leviathan', '', '', '')
    FilthyPrio.SetPrio('Pyrite Infuser', '', '', '')
    FilthyPrio.SetPrio('Gilded Steel Legplates', '', '', '')
    FilthyPrio.SetPrio('Handguards of Potent Cures', '', '', '')
    FilthyPrio.SetPrio('Mantle of Fiery Vengeance', '', '', '')
    FilthyPrio.SetPrio('Shimmering Seal', '', '', '')
    FilthyPrio.SetPrio('Twirling Blades', '', '', '')
    FilthyPrio.SetPrio('Constructor\'s Handwraps', '', '', '')
    FilthyPrio.SetPrio('Embrace of the Leviathan', '', '', '')
    FilthyPrio.SetPrio('Freya\'s Choker of Warding', '', '', '')
    FilthyPrio.SetPrio('Gloves of the Fiery Behemoth', '', '', '')
    FilthyPrio.SetPrio('Glowing Ring of Reclamation', '', '', '')
    FilthyPrio.SetPrio('Iron Riveted War Helm', '', '', '')
    FilthyPrio.SetPrio('Leviathan Fueling Manual', '', '', '')
    FilthyPrio.SetPrio('Mechanist\'s Bindings', '', '', '')
    FilthyPrio.SetPrio('Mimiron\'s Inferno Couplings', '', '', '')
    FilthyPrio.SetPrio('Steamcaller\'s Totem', '', '', '')
    FilthyPrio.SetPrio('Steamworker\'s Goggles', '', '', '')
    FilthyPrio.SetPrio('Strength of the Automaton', '', '', '')
    FilthyPrio.SetPrio('The Leviathan\'s Coil', '', '', '')
    FilthyPrio.SetPrio('Rising Sun', '', '', '')
    FilthyPrio.SetPrio('Titanguard', '', '', '')
    FilthyPrio.SetPrio('Boots of Fiery Resolution', '', '', '')
    FilthyPrio.SetPrio('Golden Saronite Dragon', '', '', '')
    FilthyPrio.SetPrio('Pendant of Fiery Havoc', '', '', '')
    FilthyPrio.SetPrio('Plated Leggings of Ruination', '', '', '')
    FilthyPrio.SetPrio('Shoulderpads of Dormant Energies', '', '', '')
    FilthyPrio.SetPrio('Cable of the Metrognome', '', '', '')
    FilthyPrio.SetPrio('Helm of the Wayward Conqueror', '', '', '')
    FilthyPrio.SetPrio('Helm of the Wayward Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Pulse Baton', '', '', '')
    FilthyPrio.SetPrio('Static Charge Handwraps', '', '', '')
    FilthyPrio.SetPrio('Stylish Power Cape', '', '', '')
    FilthyPrio.SetPrio('Helm of the Wayward Protector', '', '', '')
    FilthyPrio.SetPrio('Shoulderguards of Assimilation', '', '', '')
    FilthyPrio.SetPrio('Fused Alloy Legplates', '', '', '')
    FilthyPrio.SetPrio('Greaves of the Iron Army', '', '', '')
    FilthyPrio.SetPrio('Mimiron\'s Flight Goggles', '', '', '')
    FilthyPrio.SetPrio('Tempered Mercury Greaves', '', '', '')
    FilthyPrio.SetPrio('Fusion Blade', '', '', '')
    FilthyPrio.SetPrio('Asimov\'s Drape', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of the Wayward Conqueror', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of the Wayward Protector', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of the Wayward Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Pandora\'s Plea', '', '', '')
    FilthyPrio.SetPrio('Waistguard of the Creator', '', '', '')
    FilthyPrio.SetPrio('Malleable Steelweave Mantle', '', '', '')
    FilthyPrio.SetPrio('Insanity\'s Grip', '', '', '')
    FilthyPrio.SetPrio('Delirium\'s Touch', '', '', '')
    FilthyPrio.SetPrio('Armbands of Bedlam', '', '', '')
    FilthyPrio.SetPrio('Conductive Seal', '', '', '')
    FilthyPrio.SetPrio('Crown of Luminescence', '', '', '')
    FilthyPrio.SetPrio('Titanskin Cloak', '', '', '')
    FilthyPrio.SetPrio('Band of Draconic Guile', '', '', '')
    FilthyPrio.SetPrio('Binding of the Dragon Matriarch', '', '', '')
    FilthyPrio.SetPrio('Bracers of the Smothering Inferno', '', '', '')
    FilthyPrio.SetPrio('Breastplate of the Afterlife', '', '', '')
    FilthyPrio.SetPrio('Dragonsteel Faceplate', '', '', '')
    FilthyPrio.SetPrio('Eye of the Broodmother', '', '', '')
    FilthyPrio.SetPrio('Ironscale Leggings', '', '', '')
    FilthyPrio.SetPrio('Razorscale Talon', '', '', '')
    FilthyPrio.SetPrio('Stormtempered Girdle', '', '', '')
    FilthyPrio.SetPrio('Treads of the Invader', '', '', '')
    FilthyPrio.SetPrio('Belt of the Fallen Wyrm', '', '', '')
    FilthyPrio.SetPrio('Bracers of the Broodmother', '', '', '')
    FilthyPrio.SetPrio('Collar of the Wyrmhunter', '', '', '')
    FilthyPrio.SetPrio('Dragonslayer\'s Brace', '', '', '')
    FilthyPrio.SetPrio('Drape of the Drakerider', '', '', '')
    FilthyPrio.SetPrio('Libram of Discord', '', '', '')
    FilthyPrio.SetPrio('Living Flame', '', '', '')
    FilthyPrio.SetPrio('Proto-hide Leggings', '', '', '')
    FilthyPrio.SetPrio('Razorscale Shoulderguards', '', '', '')
    FilthyPrio.SetPrio('Saronite Mesh Legguards', '', '', '')
    FilthyPrio.SetPrio('Shackles of the Odalisque', '', '', '')
    FilthyPrio.SetPrio('Sigil of Deflection', '', '', '')
    FilthyPrio.SetPrio('Guiding Star', '', '', '')
    FilthyPrio.SetPrio('Remorse', '', '', '')
    FilthyPrio.SetPrio('Veranus\' Bane', '', '', '')
    FilthyPrio.SetPrio('Belt of the Blood Pit', '', '', '')
    FilthyPrio.SetPrio('Guise of the Midgard Serpent', '', '', '')
    FilthyPrio.SetPrio('Handwraps of Resonance', '', '', '')
    FilthyPrio.SetPrio('Legacy of Thunder', '', '', '')
    FilthyPrio.SetPrio('Leggings of Unstable Discharge', '', '', '')
    FilthyPrio.SetPrio('Spaulders of the Wayward Conqueror', '', '', '')
    FilthyPrio.SetPrio('Spaulders of the Wayward Protector', '', '', '')
    FilthyPrio.SetPrio('Spaulders of the Wayward Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of the Thunder God', '', '', '')
    FilthyPrio.SetPrio('Mjolnir Runestone', '', '', '')
    FilthyPrio.SetPrio('Pendant of the Shallow Grave', '', '', '')
    FilthyPrio.SetPrio('Sif\'s Remembrance', '', '', '')
    FilthyPrio.SetPrio('Combatant\'s Bootblade', '', '', '')
    FilthyPrio.SetPrio('Belt of the Betrayed', '', '', '')
    FilthyPrio.SetPrio('Crown of the Wayward Conqueror', '', '', '')
    FilthyPrio.SetPrio('Crown of the Wayward Protector', '', '', '')
    FilthyPrio.SetPrio('Crown of the Wayward Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Leggings of Lost Love', '', '', '')
    FilthyPrio.SetPrio('Scale of Fates', '', '', '')
    FilthyPrio.SetPrio('Sif\'s Promise', '', '', '')
    FilthyPrio.SetPrio('Vulmir, the Northern Tempest', 'Greetings', '', '')
    FilthyPrio.SetPrio('Embrace of the Gladiator', '', '', '')
    FilthyPrio.SetPrio('Fate\'s Clutch', '', '', '')
    FilthyPrio.SetPrio('Pauldrons of the Combatant', '', '', '')
    FilthyPrio.SetPrio('Warhelm of the Champion', '', '', '')
    FilthyPrio.SetPrio('Wisdom\'s Hold', '', '', '')
    FilthyPrio.SetPrio('Bindings of the Depths', '', '', '')
    FilthyPrio.SetPrio('Choker of the Abyss', '', '', '')
    FilthyPrio.SetPrio('Darkstone Ring', '', '', '')
    FilthyPrio.SetPrio('Gauntlets of the Wretched', '', '', '')
    FilthyPrio.SetPrio('Hoperender', '', '', '')
    FilthyPrio.SetPrio('Pendant of Endless Despair', '', '', '')
    FilthyPrio.SetPrio('Saronite Animus Cloak', '', '', '')
    FilthyPrio.SetPrio('Shadowbite', '', '', '')
    FilthyPrio.SetPrio('Underworld Mantle', '', '', '')
    FilthyPrio.SetPrio('Vestments of the Piercing Light', '', '', '')
    FilthyPrio.SetPrio('Drape of the Faceless General', '', '', '')
    FilthyPrio.SetPrio('Leggings of Profound Darkness', '', '', '')
    FilthyPrio.SetPrio('Aesuga, Hand of the Ardent Champion', '', '', '')
    FilthyPrio.SetPrio('Tortured Earth', '', '', '')
    FilthyPrio.SetPrio('Void Sabre', '', '', '')
    FilthyPrio.SetPrio('Belt of Clinging Hope', '', '', '')
    FilthyPrio.SetPrio('Belt of the Darkspeaker', '', '', '')
    FilthyPrio.SetPrio('Boots of the Forgotten Depths', '', '', '')
    FilthyPrio.SetPrio('Boots of the Underdweller', '', '', '')
    FilthyPrio.SetPrio('Darkcore Leggings', '', '', '')
    FilthyPrio.SetPrio('Grips of the Unbroken', '', '', '')
    FilthyPrio.SetPrio('Helm of the Faceless', '', '', '')
    FilthyPrio.SetPrio('Idol of the Corruptor', '', '', '')
    FilthyPrio.SetPrio('Libram of the Sacred Shield', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Unknowing', '', '', '')
    FilthyPrio.SetPrio('Metallic Loop of the Sufferer', '', '', '')
    FilthyPrio.SetPrio('Ring of the Vacant Eye', '', '', '')
    FilthyPrio.SetPrio('The General\'s Heart', '', '', '')
    FilthyPrio.SetPrio('Scepter of Lost Souls', '', '', '')
    FilthyPrio.SetPrio('Lotrafen, Spear of the Damned', '', '', '')
    FilthyPrio.SetPrio('Flare of the Heavens', '', '', '')
    FilthyPrio.SetPrio('Handwraps of the Vigilant', '', '', '')
    FilthyPrio.SetPrio('Pendulum of Infinity', '', '', '')
    FilthyPrio.SetPrio('Vestments of the Blind Denizen', '', '', '')
    FilthyPrio.SetPrio('Voldrethar, Dark Blade of Oblivion', '', '', '')
    FilthyPrio.SetPrio('Armbands of the Construct', '', '', '')
    FilthyPrio.SetPrio('Chestplate of Vicious Potency', '', '', '')
    FilthyPrio.SetPrio('Conductive Cord', '', '', '')
    FilthyPrio.SetPrio('Gloves of Taut Grip', '', '', '')
    FilthyPrio.SetPrio('Helm of Veiled Energies', '', '', '')
    FilthyPrio.SetPrio('Plasma Foil', '', '', '')
    FilthyPrio.SetPrio('Power Enhancing Loop', '', '', '')
    FilthyPrio.SetPrio('Pulsing Spellshield', '', '', '')
    FilthyPrio.SetPrio('Treacherous Shoulderpads', '', '', '')
    FilthyPrio.SetPrio('Vest of the Glowing Crescent', '', '', '')
    FilthyPrio.SetPrio('Breastplate of the Stoneshaper', '', '', '')
    FilthyPrio.SetPrio('Fluxing Energy Coils', '', '', '')
    FilthyPrio.SetPrio('Seal of Ulduar', '', '', '')
    FilthyPrio.SetPrio('Aesir\'s Edge', '', '', '')
    FilthyPrio.SetPrio('Magnetized Projectile Emitter', '', '', '')
    FilthyPrio.SetPrio('Boots of Hasty Revival', '', '', '')
    FilthyPrio.SetPrio('Brass-lined Boots', '', '', '')
    FilthyPrio.SetPrio('Clockwork Legplates', '', '', '')
    FilthyPrio.SetPrio('Crazed Construct Ring', '', '', '')
    FilthyPrio.SetPrio('Horologist\'s Wristguards', '', '', '')
    FilthyPrio.SetPrio('Mantle of Wavering Calm', '', '', '')
    FilthyPrio.SetPrio('Quartz-studded Harness', '', '', '')
    FilthyPrio.SetPrio('Sandals of Rash Temperament', '', '', '')
    FilthyPrio.SetPrio('Shoulderplates of the Deconstructor', '', '', '')
    FilthyPrio.SetPrio('Sigil of the Vengeful Heart', '', '', '')
    FilthyPrio.SetPrio('Signet of the Earthshaker', '', '', '')
    FilthyPrio.SetPrio('Thunderfall Totem', '', '', '')
    FilthyPrio.SetPrio('Golem-Shard Sticker', 'Dof', '', '')
    FilthyPrio.SetPrio('Quartz Crystal Wand', '', '', '')
    FilthyPrio.SetPrio('Twisted Visage', '', '', '')
    FilthyPrio.SetPrio('Breastplate of the Devoted', '', '', '')
    FilthyPrio.SetPrio('Charm of Meticulous Timing', '', '', '')
    FilthyPrio.SetPrio('Gloves of the Steady Hand', '', '', '')
    FilthyPrio.SetPrio('Grasps of Reason', '', '', '')
    FilthyPrio.SetPrio('Sorthalis, Hammer of the Watchers', '', '', '')
    FilthyPrio.SetPrio('Abaddon', '', '', '')
    FilthyPrio.SetPrio('Chestguard of the Wayward Conqueror', '', '', '')
    FilthyPrio.SetPrio('Chestguard of the Wayward Protector', '', '', '')
    FilthyPrio.SetPrio('Chestguard of the Wayward Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Deliverance', '', '', '')
    FilthyPrio.SetPrio('Devotion', '', '', '')
    FilthyPrio.SetPrio('Faceguard of the Eyeless Horror', '', '', '')
    FilthyPrio.SetPrio('Kingsbane', '', '', '')
    FilthyPrio.SetPrio('Leggings of the Insatiable', '', '', '')
    FilthyPrio.SetPrio('Pendant of a Thousand Maws', '', '', '')
    FilthyPrio.SetPrio('Royal Seal of King Llane', '', '', '')
    FilthyPrio.SetPrio('Touch of Madness', '', '', '')
    FilthyPrio.SetPrio('Treads of the Dragon Council', '', '', '')
    FilthyPrio.SetPrio('Amice of Inconceivable Horror', '', '', '')
    FilthyPrio.SetPrio('Signet of Soft Lament', '', '', '')
    FilthyPrio.SetPrio('Soul-Devouring Cinch', '', '', '')
    FilthyPrio.SetPrio('Vanquished Clutches of Yogg-Saron', '', '', '')
    FilthyPrio.SetPrio('Caress of Insanity', '', '', '')
    FilthyPrio.SetPrio('Blood of the Old God', '', '', '')
    FilthyPrio.SetPrio('Chestguard of Insidious Intent', '', '', '')
    FilthyPrio.SetPrio('Chestguard of the Fallen God', '', '', '')
    FilthyPrio.SetPrio('Cowl of Dark Whispers', '', '', '')
    FilthyPrio.SetPrio('Garona\'s Guise', '', '', '')
    FilthyPrio.SetPrio('Godbane Signet', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Wayward Conqueror', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Wayward Protector', '', '', '')
    FilthyPrio.SetPrio('Mantle of the Wayward Vanquisher', '', '', '')
    FilthyPrio.SetPrio('Sanity\'s Bond', '', '', '')
    FilthyPrio.SetPrio('Shawl of Haunted Memories', '', '', '')
    FilthyPrio.SetPrio('Soulscribe', '', '', '')
    FilthyPrio.SetPrio('Earthshaper', '', '', '')
    FilthyPrio.SetPrio('Hammer of Crushing Whispers', '', '', '')
    FilthyPrio.SetPrio('Dark Edge of Depravity', '', '', '')
    FilthyPrio.SetPrio('Legguards of Cunning Deception', '', '', '')
    FilthyPrio.SetPrio('Seal of the Betrayed King', '', '', '')
    FilthyPrio.SetPrio('Show of Faith', '', '', '')
    FilthyPrio.SetPrio('Treads of the False Oracle', '', '', '')
    FilthyPrio.SetPrio('Mimiron\'s Head', '', '', '')
    FilthyPrio.SetPrio('Belt of the Sleeper', '', '', '')
    FilthyPrio.SetPrio('Bladebearer\'s Signet', '', '', '')
    FilthyPrio.SetPrio('Daschal\'s Bite', '', '', '')
    FilthyPrio.SetPrio('Greaves of the Stonewarder', '', '', '')
    FilthyPrio.SetPrio('Grips of Chaos', '', '', '')
    FilthyPrio.SetPrio('Idol of the Flourishing Life', '', '', '')
    FilthyPrio.SetPrio('Leggings of the Tortured Earth', '', '', '')
    FilthyPrio.SetPrio('Pendant of Focused Energies', '', '', '')
    FilthyPrio.SetPrio('Relic Hunter\'s Cord', '', '', '')
    FilthyPrio.SetPrio('Shoulders of Misfortune', '', '', '')
    FilthyPrio.SetPrio('Shroud of Alteration', '', '', '')
    FilthyPrio.SetPrio('Titanstone Pendant', '', '', '')
end
