--[[

Generate loot priorities for phase 1 items.

Usage:
set_prio('ITEM NAME', 'ITEM PRIORITY', 'ITEM NOTES', 'WHO HAS ITEM ALREADY')

Example:
set_prio('Thunderfury, Blessed Blade of the Windseeker', 'Best Tank > Worst Tank', 'Did someone say...?', '')

This will put the following on the 'Thunderfury, Blessed Blade of the Windseeker' item tooltip.

Loot Prio: Best Tank > Worst Tank
Notes: Did someone say...?

The 'Has Item' part will not display because it is blank.

]]--

-- Last updated: 27/10/2022 06:03:06 PM
set_prio('Cloak of Averted Crisis', 'RFI', 'Filler', 'Thor, Chris, Jules')
set_prio('Shawl of the Old Maid', 'MS>OS Roll', 'Filler', 'Aaron, Shazz')
set_prio('Shroud of Luminosity', 'MS>OS Roll', '', 'Thor')
set_prio('Heritage', 'Msg', 'Slight upgrade over badge neck', '')
set_prio('Thunderstorm Amulet', 'MS>OS Roll', '', 'Shazz')
set_prio('Lost Jewel', 'MS>OS Roll', 'BIS for anyone else?', 'Chris, Aaron, Samme')
set_prio('Sand-Worn Band', 'MS>OS Roll', 'Better than JC ring but not bis', '')
set_prio('Seized Beauty', 'RFI', 'Main healers dont want crit, give to OS healers', 'Ethos')
set_prio('Defender\'s Code', 'MS>OS Roll', 'bear OS maybe', '')
set_prio('Dying Curse', 'Thor', 'BiS for every caster to save hit elsewhere', 'Aaron, Cypack')
set_prio('Forethought Talisman', 'Ethos > HPals/RFI', 'BiS throughput after Illustration of the Dragon Soul', 'Cluelust')
set_prio('Cloak of the Shadowed Sun', 'MS>OS Roll', 'badge cloak is bis> armour set', '')
set_prio('Fool\'s Trial', 'MS>OS Roll', 'Filler until Quest neck - prio people last in line', 'Sandra')
set_prio('Ruthlessness', 'Trisp?', 'BIS: Frost & Unholy', 'Tobs, Greetings, Msg')
set_prio('Strong-Handed Ring', 'Verge? > Hunters', 'Rogue BiS according to Inkies/hunters', 'Inkeyes')
set_prio('Grim Toll', 'Hov > Trisp > Coonixx', 'BIS: Feral / Warrior', '')
set_prio('Shadow of the Ghoul', 'OS', 'Block set Fig > OS', 'Trisp')
set_prio('Boots of the Escaped Captive', 'MS>OS Roll', 'Minor upgrade over Wyrmrest exalted boots', 'Chris')
set_prio('Ousted Bead Necklace', 'MS>OS Roll', 'Badge neck is better.', '')
set_prio('Haunting Call', 'MS>OS Roll', 'Whoever needs it at the time', '')
set_prio('Silent Crusader', 'Tobs', 'Frost DK > Unholy > Rogue', 'Greetings')
set_prio('Shoulderpads of the Undaunted', 'Does Koro want for hit?', 'Possibly Koro for the hit', '')
set_prio('Inevitable Defeat', 'RFI?', 'Hawkey > the rest', 'Hawkey')
set_prio('Corpse Scarab Handguards', 'RFI', 'Filler', 'Cluelust')
set_prio('Rescinding Grips', 'RFI', 'Worse than tier gloves', '')
set_prio('Leggings of Atrophy', 'MS>OS Roll', 'Filler', '')
set_prio('Inexorable Sabatons', 'MS>OS Roll', 'Fig then OS', 'Fig')
set_prio('Chains of Adoration', 'Cluelust > Sterile', 'BiS non-quest neck RSham and HPal', 'Jess')
set_prio('Shield of Assimilation', 'Jess > Cluelust > Sterile', 'Second BiS RSham, HPal and Ele', '')
set_prio('Pauldrons of Unnatural Death', 'MS>OS Roll', 'hawkey', 'Hawkey')
set_prio('Mantle of the Locusts', 'RFI', 'BiS: RDruid', 'Shazz')
set_prio('Dawnwalkers', 'koro', 'Filler', '')
set_prio('Sash of the Parlor', 'RFI', 'Filler', 'Ethos')
set_prio('Gemmed Wand of the Nerubians', 'Samme', 'BiS:Arcane Mage/Spriest', 'Zlips, Zeforr')
set_prio('Swarm Bindings', 'MS>OS Roll', 'Filler', '')
set_prio('Sabatons of Sudden Revival', 'Tobs > Msg', 'BIS Frost DK / Close second BIS for Unholy', '')
set_prio('Webbed Death', 'Verge > Inkies > Hunters', 'BIS Rogues and Hunter DW', '')
set_prio('Arachnoid Gold Band', 'MS>OS Roll', '', '')
set_prio('Cult\'s Chestguard', 'MS>OS Roll', 'Filler', '')
set_prio('Tunic of Prejudice', 'MS>OS Roll', '', '')
set_prio('Atonement Greaves', 'RFI', 'Filler', 'Thor')
set_prio('Callous-Hearted Gauntlets', 'OS', 'avoidance set maybe, not bis over tier', 'Hawkey')
set_prio('Gloves of Token Respect', 'Heasy', 'Arcane Bis - But who first?', '')
set_prio('Faerlina\'s Madness', 'MS>OS Roll', '', '')
set_prio('Epaulets of the Grieving Servant', 'RFI', 'Filler', '')
set_prio('Belt of False Dignity', 'MS>OS Roll', 'Filler', '')
set_prio('Totem of Misery', 'RFI', 'Also from Boj?', '')
set_prio('Punctilious Bindings', 'MS>OS Roll', '', 'Samme')
set_prio('Dislocating Handguards', 'MS>OS Roll', 'Filler', 'Inkeyes')
set_prio('Fire-Scorched Greathelm', 'MS>OS Roll', 'Filler', '')
set_prio('Widow\'s Fury', 'Tobs/Msg?', 'Unholy fillter?', '')
set_prio('Idol of Worship', 'MS>OS Roll', 'Also from Boj?', 'Coonixx')
set_prio('Bracers of the Tyrant', 'Greetings > Trisp?', 'BIS Frost / Arms - (Greetings needs for expertise cap)', 'Tobs')
set_prio('Aged Winter Cloak', 'Jolie > Coonixx > Hov', 'BIS War and maybe Feral', 'Trisp')
set_prio('Undiminished Battleplate', 'MS>OS Roll', 'Filler', '')
set_prio('Digested Silken Robes', 'MS>OS Roll', '', '')
set_prio('Quivering Tunic', 'Cluelust  > RFI', 'Filler', '')
set_prio('Ablative Chitin Girdle', 'Fig > Hawkey', 'Bis both tanks  fig>hawkey', '')
set_prio('Bindings of the Hapless Prey', 'MS>OS Roll', '', 'Fig')
set_prio('Cowl of the Perished', 'MS>OS Roll', '', '')
set_prio('Helm of Diminished Pride', 'DE', 'Bad', '')
set_prio('Distorted Limbs', 'MS>OS Roll', '', '')
set_prio('Wraith Strike', 'MS>OS Roll', '', '')
set_prio('Matriarch\'s Spawn', 'Aaron', 'Demo/Aff', '')
set_prio('Mantle of Scattered Kinship', 'MS>OS Roll', '', 'Chris')
set_prio('Infectious Skitterer Leggings', 'MS>OS Roll', '', 'Coonixx')
set_prio('The Jawbone', 'OS/DE', 'BIS Ret AoE or something... (because overall damage is bis)', 'Koro')
set_prio('Torn Web Wrapping', 'Pili', 'BIS Hunter?', '')
set_prio('Sinner\'s Bindings', 'MS>OS Roll', 'fury? rogue if they want to break 2 set t6', '')
set_prio('Gloves of Calculated Risk', 'MS>OS Roll', 'Hunter filler', 'Pili')
set_prio('Crude Discolored Battlegrips', 'MS>OS Roll', 'Filler', 'Trisp')
set_prio('Boots of Septic Wounds', 'MS>OS Roll', '', '')
set_prio('Boots of Persuasion', 'MS>OS Roll', '', '')
set_prio('Surplus Limb', 'Samme', 'Arcane mage/Spriest', 'Heasy')
set_prio('Fleshless Girdle', 'MS>OS Roll', 'block set but most likely wasted item', '')
set_prio('Waistguard of Divine Grace', 'Sterile > Saicere > RFI', 'Super minor for both', '')
set_prio('Hero\'s Surrender', 'MS>OS Roll', '', 'Jolie')
set_prio('Libram of Tolerance', 'RFI', 'meh', '')
set_prio('Girdle of the Gambit', 'Cluelust', 'bis RSham', 'Thor')
set_prio('Sash of Solitude', 'Ethos > RFI', '', '')
set_prio('Totem of Hex', 'MS>OS Roll', '', 'Died')
set_prio('Split Greathammer', 'Tobs/Msg?', 'Unholy fillter?', '')
set_prio('Arrowsong', 'MS>OS Roll', 'Physical next? Pretty sure beanpole has it', 'Beanpole')
set_prio('Belt of the Tortured', 'Verge > Sandra', 'ret/rogue bis - prio rogue', 'Inkeyes')
set_prio('Tunic of Indulgence', 'MS>OS Roll', 'Filler', '')
set_prio('Fallout Impervious Tunic', 'MS>OS Roll', '', 'Thor')
set_prio('Cowl of Vanity', 'RFI', '', 'Zlips, Samme')
set_prio('Chestguard of the Exhausted', 'MS>OS Roll', 'tier just better both tanks OS', '')
set_prio('Desecrated Past', 'MS>OS Roll', '', '')
set_prio('Plague Igniter', 'MS>OS Roll', '', '')
set_prio('Sympathetic Amice', 'RFI', '', '')
set_prio('Mantle of the Fatigued Sage', 'MS>OS Roll', '', '')
set_prio('Spaulders of Incoherence', 'RFI', 'worse than tier', '')
set_prio('Bracers of Liberation', 'Jess if no Valor bracers', '', '')
set_prio('Twilight Mist', 'MS>OS Roll', 'Rogue / Hunter filler?', '')
set_prio('Origin of Nightmares', 'MS>OS Roll', 'fillter - prio kitties', '')
set_prio('Depraved Linked Belt', 'Beanpole > Died', 'BIS: Hunter, Enhance - 2nd bis?', 'Pili')
set_prio('Girdle of Chivalry', 'Greetings > Tobs? > Koro?', 'BIS Unholy > Frost DK - depending on setup, ret', 'Msg')
set_prio('Slime Stream Bands', 'Pili > Died', 'BIS: Hunter, Enhance', 'Beanpole')
set_prio('Cover of Silence', 'MS>OS Roll', 'Filler', '')
set_prio('Riveted Abomination Leggings', 'Msg > Tobs', 'BIS Unholy', '')
set_prio('Legplates of the Lost Conqueror', 'MS>OS Roll', 'Prot > Holy > RFI', 'Fig, Jess, Sterile, Koro, Shazz')
set_prio('Legplates of the Lost Protector', 'Trisp?', 'Enhance > Hunter > Resto > Fury', 'Died, Beanpole, Pili, Cluelust')
set_prio('Legplates of the Lost Vanquisher', 'RFI MS > Chris Resto?', 'Frost DK > Rogue > Mage', 'Greetings, Tobs, Inkies, Verge, Jules, Heasy, Samme')
set_prio('Benefactor\'s Gauntlets', 'MS>OS Roll', 'BoE', '')
set_prio('Wraps of the Persecuted', 'RFI', '', 'Zeforr')
set_prio('Faceguard of the Succumbed', 'Sterile > OS', '', 'Jess')
set_prio('Headpiece of Fungal Bloom', 'Sterile/Cluelust? > RFI', 'Filler / Sterile or Cluelust if no tier helm', 'Chris')
set_prio('Pauldrons of the Abandoned', 'MS>OS Roll', '', '')
set_prio('Sabatons of Endurance', 'Fig > Hawkey', 'both tanks bis   fig>hawkey', '')
set_prio('Spire of Sunset', 'RFI', '', 'Cluelust')
set_prio('Cincture of Polarity', 'Thor', '', '')
set_prio('Tunic of Masked Suffering', 'MS>OS Roll', 'Filler', 'Beanpole')
set_prio('Crippled Treads', 'Aaron? > ???????????', 'Filler hunter / enh', '')
set_prio('Robes of Mutation', 'MS>OS Roll', '', '')
set_prio('Poignant Sabatons', 'Sell', 'BoE', 'Sterile, Jess')
set_prio('Gloves of the Fallen Wizard', 'MS>OS Roll', '', '')
set_prio('Libram of Radiance', 'Koro? > OS', '', '')
set_prio('Gauntlets of the Disobedient', 'MS>OS Roll', 'block set', '')
set_prio('Legguards of the Undisturbed', 'RFI', '', '')
set_prio('Accursed Spine', 'MS>OS Roll', '', 'Chris')
set_prio('Belt of Potent Chanting', 'MS>OS Roll', '', '')
set_prio('Bands of Impurity', 'MS>OS Roll', '', 'Cypack')
set_prio('Angry Dread', 'Greetings > Greetings > Tobs > Tobs', 'BIS Frost dks', '')
set_prio('Shoulderguards of Opportunity', 'MS>OS Roll', 'People looking for the next opportunity', '')
set_prio('Spinning Fate', 'MS>OS Roll', 'good hit option for thrown, consult war/rogue', '')
set_prio('Thrusting Bands', 'Rogue?', 'ret bis', 'Koro')
set_prio('Iron-Spring Jumpers', 'Trisp > Any DK want? > Sell', 'BoE item - decent hit piece for warr/dk', '')
set_prio('Leggings of Colossal Strides', 'MS>OS Roll', '', '')
set_prio('Eruption-Scarred Boots', 'MS>OS Roll', '', '')
set_prio('Breastplate of Tormented Rage', 'MS>OS Roll', 'not better than tier', '')
set_prio('Chestguard of Bitter Charms', 'DE', 'bad', '')
set_prio('Heigan\'s Putrid Vestments', 'Zlips > Zeforr', 'BIS: Spriest', '')
set_prio('Serene Echoes', 'RFI', '', 'Shazz')
set_prio('Gloves of the Dancing Bear', 'MS>OS Roll', '', '')
set_prio('Helm of Pilgrimage', 'DE', 'no meta', '')
set_prio('Legguards of the Apostle', 'RFI', '', '')
set_prio('Bindings of the Decrepit', 'Cluelust > RFI', '', '')
set_prio('Sigil of Awareness', 'Hawkey > Msg', 'BIS Frost DK', 'Greetings, Tobs')
set_prio('Cryptfiend\'s Bite', 'Hov?', 'fillter - prio kitties', '')
set_prio('The Undeath Carrier', 'Hov?', 'fillter - prio kitties', 'Coonixx')
set_prio('Stalk-Skin Belt', 'Inkies > Verge > trisp', 'BIS Rogue - confirm bis with rogues - patchwerk may be better, fury', '')
set_prio('Footwraps of Vile Deceit', 'hov', 'BiS: Feral, Rogue', '')
set_prio('Grotesque Handgrips', 'MS>OS Roll', 'Filler', 'Beanpole')
set_prio('The Hand of Nerub', 'MS>OS Roll', 'Hunter filler?', '')
set_prio('Mantle of the Lost Conqueror', 'Shazz', 'Prot > ?? (Holy, Ret, Disc, Shadow, Demo, Aff)', 'Fig, Sandra, Aaron, Ethos, Sterile, Jess, Cypack')
set_prio('Mantle of the Lost Protector', 'RFI or OS', 'Enhance > ?? (Arms, Hunter, Resto)', 'Died, Trisp, Cluelust, Pili, Beanpole')
set_prio('Mantle of the Lost Vanquisher', 'Hawkey? > Inkies > Jules > Heasy', 'Balance > Frost DK > Blood DK > Rogue > Mage', 'Chris, Greetings, Tobs, Hovden, Samme, Verge')
set_prio('Vest of Vitality', 'RFI', '', '')
set_prio('Boots of Impetuous Ideals', 'MS>OS Roll', 'BoE', '')
set_prio('Cowl of Innocent Delight', 'OS/DE', 'no meta', '')
set_prio('The Impossible Dream', 'MS>OS Roll', '', '')
set_prio('Greaves of Turbulence', 'MS>OS Roll', 'block set', 'Trisp')
set_prio('Girdle of Unity', 'DE/OS', '', '')
set_prio('Fading Glow', 'RFI', '', 'Zeforr')
set_prio('Chestpiece of Suspicion', 'MS>OS Roll', 'Filler for suspicious folk', 'Verge')
set_prio('Legplates of Double Strikes', 'Trisp', 'BiS Arms/Fury', '')
set_prio('Boots of Forlorn Wishes', 'MS>OS Roll', '', '')
set_prio('Faithful Steel Sabatons', 'DE/OS', '', '')
set_prio('Gauntlets of Guiding Touch', 'RFI', 'Good but Hpals run tier', '')
set_prio('Bracers of the Unholy Knight', 'Hawkey', 'BIS: dk > not in figs set', '')
set_prio('Girdle of Recuperation', 'MS>OS Roll', 'Ele Shaman', '')
set_prio('Bands of Mutual Respect', 'Thor', 'Ele Shaman', '')
set_prio('Bindings of the Expansive Mind', 'MS>OS Roll', 'Filler', '')
set_prio('Esteemed Bindings', 'MS>OS Roll', '', 'Chris')
set_prio('Idol of the Shooting Star', 'MS>OS Roll', '', '')
set_prio('Spaulders of Egotism', 'MS>OS Roll', 'BoE', '')
set_prio('Shoulderpads of Secret Arts', 'MS>OS Roll', '', '')
set_prio('Totem of Dueling', 'Died?', 'legitimate duelers only', '')
set_prio('Girdle of Razuvious', 'Tobs > Greetings? > Trisp', 'BiS Arms/Frost DK', '')
set_prio('Hood of the Exodus', 'Rogue/War?', 'Filler', 'Coonixx, Hov')
set_prio('Leggings of Fleeting Moments', 'MS>OS Roll', '', '')
set_prio('Leggings of Failed Escape', 'MS>OS Roll', '', '')
set_prio('Gothik\'s Cowl', 'MS>OS Roll', '', '')
set_prio('Helm of Unleashed Energy', 'MS>OS Roll', 'Filler for Rsham until Tier', 'Cluelust if no Tier helm')
set_prio('Burdened Shoulderplates', 'Fig', 'block set', '')
set_prio('Life and Death', 'Azz', '', 'Samme, Cypack, Sterile')
set_prio('Shackled Cinch', 'MS>OS Roll', '', '')
set_prio('Helm of Vital Protection', 'MS>OS Roll', 'pretty decent helm very similar to tier but 4pc', '')
set_prio('Idol of Awakening', 'DE/OS', '', 'Chris')
set_prio('Libram of Resurgence', 'MS>OS Roll', '', '')
set_prio('Touch of Horror', 'DE/OS', '', '')
set_prio('Abetment Bracers', 'Jess > Sterile', '', '')
set_prio('Bindings of Yearning', 'AH', 'Prot > Demo > Aff > Ret > Holy', '')
set_prio('Bracers of Unrelenting Attack', 'Msg > Trisp?', 'BIS Unholy, Arms, Frost - depending on setup', '')
set_prio('Zeliek\'s Gauntlets', 'Msg?', 'BiS Unholy DK/decent for fury', '')
set_prio('Helm of the Grave', 'MS>OS Roll', 'Filler', '')
set_prio('Final Voyage', 'Beanpole? > Rogues', 'Hunters if they want, then melee', '')
set_prio('Breastplate of the Lost Conqueror', 'Koro > Jess > Sterile', 'Tank > DPS > Healer', 'Fig, Aaron, Cypack')
set_prio('Breastplate of the Lost Protector', 'Thor > Cluelust', 'Enhance > Ele > Resto > Arms', 'Died')
set_prio('Breastplate of the Lost Vanquisher', 'Mages', 'Balance > Blood DK > Frost/Unholy > Rogue > Mage (Give 10 man to Mage > Rogue)', 'Chris, Hawkey, Msg, Greetings, Tobs, Inkies, Verge')
set_prio('Broken Promise', 'OS', 'Tank stuff', 'Hawkey')
set_prio('Gloves of Peaceful Death', 'MS>OS Roll', '', '')
set_prio('Leggings of Voracious Shadows', 'MS>OS Roll', '', 'Thor')
set_prio('Urn of Lost Memories', 'Ethos > OS', '', '')
set_prio('Mantle of the Corrupted', 'MS>OS Roll', '', '')
set_prio('Damnation', 'MS>OS Roll', '', '')
set_prio('Armageddon', 'MS>OS Roll', 'fillter', 'Koro, Greetings')
set_prio('Breastplate of Frozen Pain', 'MS>OS Roll', 'Filler', 'Sterile')
set_prio('Boots of the Great Construct', 'Died', 'BIS Enh?', '')
set_prio('Gloves of Fast Reactions', 'MS>OS Roll', 'BoE', '')
set_prio('Icy Blast Amulet', 'Hunter', '2nd BIS for Rogues', 'Inkies, Verge')
set_prio('Murder', 'MS>OS Roll', 'Rogue / Hunter filler?', '')
set_prio('Key to the Focusing Iris', 'MS>OS Roll', '10 man key to keep track', 'Squirties, Beanpole, Coonixx, Heasy, Died, Cypack, Aaron, Zeforr, Inkies')
set_prio('Heroic Key to the Focusing Iris', 'Pili', 'Prio fig first then dps > healers - consider who has 10 man necks that are generally 2nd bis?', 'Fig, Thor, Trisp')
set_prio('Sympathy', 'Ethos if no Maly robes', 'Filler', '')
set_prio('Bandit\'s Insignia', 'MS>OS Roll', 'dogshit', '')
set_prio('Gloves of Grandeur', 'MS>OS Roll', '', '')
set_prio('Bone-Inlaid Legguards', 'OS/DE', 'meh', '')
set_prio('Legguards of the Boneyard', 'MS>OS Roll', '', '')
set_prio('Gatekeeper', 'Fig > Hawkey', 'fig>hawkey bis', '')
set_prio('Legwraps of the Defeated Dragon', 'MS>OS Roll', 'Filler', 'Shazz')
set_prio('Ceaseless Pity', 'RFI', '', '')
set_prio('Cosmic Lights', 'MS>OS Roll', 'Filler', '')
set_prio('Ring of Decaying Beauty', 'Jess > RFI', '', 'Cluelust')
set_prio('Platehelm of the Great Wyrm', 'MS>OS Roll', 'block set', '')
set_prio('Noble Birthright Pauldrons', 'RFI', 'Hpals run tier instead', '')
set_prio('Rune of Repulsion', 'MS>OS Roll', 'avoidance set maybe, weird item', '')
set_prio('Extract of Necromantic Power', 'spriest', '', '')
set_prio('Soul of the Dead', 'Cluelust > RFI', 'Maybe BiS: RSham, HPal', '')
set_prio('Drape of the Deadly Foe', 'Msg > Bean', 'BiS: Rogue, Hunter, Frost, Unholy, Ret, Feral', 'Verge')
set_prio('Calamity\'s Grasp', 'Died > Rogues', 'BiS: Combat and Enh', '')
set_prio('Last Laugh', 'Msg > Tobs > Hawkey', 'BiS: Prot > Unh > Blood', 'Fig')
set_prio('Sinister Revenge', 'Inkies > Hunters', 'BIS Assassin Rogue & Hunter DW', 'Verge')
set_prio('Envoy of Mortality', 'Pili > Bean', 'BiS: Hunter and Rogue - consider pili for dwarf gun prio', '')
set_prio('Crown of the Lost Conqueror', 'Azz > Sandra', 'Prot > Demo > Aff > Ret', 'Fig, Aaron, Cypack')
set_prio('Crown of the Lost Protector', 'Trisp > Cluelust', 'Ele > Arms > Resto', 'Thor')
set_prio('Crown of the Lost Vanquisher', 'Inkies > Verge > Coonixx > Hov', 'Balance > Blood DK > Rogue > Feral > Mage', 'Chris, Hawkey')
set_prio('Boundless Ambition', 'Fig', 'BiS: Blood and Prot (Armor)', 'Hawkey')
set_prio('Cape of the Unworthy Wizard', 'Ethos', 'BiS: Disc/Demo', '')
set_prio('Betrayer of Humanity', 'Warrior based on 10 man loot', 'BiS: Arms, Ret, Unholy, Blood?', '')
set_prio('Journey\'s End', 'Coonixx or Hov?', 'BiS: Feral/Hunter -  Hov has 10m KT, Coon has 25m Heigen', '')
set_prio('Leggings of Mortal Arrogance', 'Aaron', 'BiS: Disc/Demo', 'Ethos')
set_prio('The Turning Tide', 'Jules', 'BiS HPal weapon after a long line of casters', 'Aaron')
set_prio('Torch of Holy Fire', 'Thor > Check who is having mana issues', 'BiS: Disc, RDruid, RSham, Ele, Spriest', 'Jess')
set_prio('Voice of Reason', 'Thor > Sterile > Jess > Cluelust', 'BiS: Ele, RSham and HPal', '')
set_prio('Signet of Manifested Pain', 'Samme', 'BiS: Literally every SP user, reward pumpers (possibly enh bis too)', '')
set_prio('Wall of Terror', 'Trisp > OS', 'BiS: Prot', 'Fig')
set_prio('Hyaline Helm of the Sniper', 'MS>OS Roll', 'Filler', '')
set_prio('Concealment Shoulderpads', 'Probs Feral', 'Filler', 'Verge')
set_prio('Fury of the Five Flights', 'Pili or Beanpole', 'BiS: Ret, Trap-weave Hunter', 'Sandra')
set_prio('Gauntlets of the Lost Conqueror', 'locks > hpals > spriest > ethos', 'fig > demo > hpal > spriest > ret = aff > disc', 'Fig, Icantwalk')
set_prio('Gauntlets of the Lost Protector', 'RFI MS or OS', 'Enh > ??', 'Died, Trisp')
set_prio('Gauntlets of the Lost Vanquisher', 'Hawkey > Greetings > Tobs', 'Balance > Blood DK > Frost DK > Arcane', 'Chris')
set_prio('Chestplate of the Great Aspects', 'RFI', 'Filler', '')
set_prio('Wyrmrest Band', 'Ethos > Saicere > Cluelust', 'BiS: Disc, top 4 option for the other healers', 'Sterile')
set_prio('Dragon Brood Legguards', 'MS>OS Roll', 'Filler', '')
set_prio('Council Chamber Epaulets', 'RFI', 'Filler', '')
set_prio('Mantle of the Eternal Sentinel', 'MS>OS Roll', 'BoE, good for Ele if they dont need hit, filler for HPal/RSham/Balance', '')
set_prio('Illustration of the Dragon Soul', 'Zef > Who Pumps?', 'yell at ethos if this buff ever drops', 'Ethos')
set_prio('Staff of Restraint', 'MS>OS Roll', 'Filler, Everyone wants 1h+oh over staves', '')
set_prio('Upstanding Spaulders', 'RFI', 'Filler', '')
set_prio('The Sanctum\'s Flowing Vestments', 'Samme', 'BiS: Spriest, Arcane', 'Zeforr, Jules')
set_prio('Dragonstorm Breastplate', 'MS>OS Roll', 'Blood?', '')
set_prio('Bountiful Gauntlets', 'MS>OS Roll', 'Filler', 'Cluelust')
set_prio('Obsidian Greathelm', 'Msg > Tobs', 'BiS: Unholy and Frost/fury', 'Greetings')
set_prio('Leggings of the Honored', 'Inkies > Coon', 'BiS: Rogue and Cat/ret', '')
set_prio('Pennant Cloak', 'Cypack', 'Highest ilvl cloak this phase + only one with a socket, bis for basically every SP user, reward pumpers', '')
set_prio('Headpiece of Reconciliation', 'MS>OS Roll', 'BiS: RDruid', 'Chris')
set_prio('Unsullied Cuffs', 'Samme', 'BiS: Disc, Spriest, Arcane, Demo, Aff, Balance, RDruid', 'Jules')
set_prio('Reins of the Twilight Drake', 'MS>OS Roll', '', 'Zlips, CHL, ')
set_prio('Chestguard of the Recluse', 'Inkies > Coonixx > Verge > Trisp', 'BiS: Cat, Rogue, Arms, Fury', 'Hovden')
set_prio('Melancholy Sabatons', 'Trisp/Jolie > Greetings > Msg', 'BiS: Arms / Frost / Unholy', '')
set_prio('Frosted Adroit Handguards', 'Bean', 'BiS: Rogue, Cat, Ret, Arms, Hunter', 'Pili')
set_prio('Blue Aspect Helm', 'Died > Beanpole', 'BiS: Enh/Hunters - reward the biggest pumper! Who will win? Bean or Died? died imo', 'Pili')
set_prio('Mark of Norgannon', 'Died?', 'Enh BiS according to wowhead?', '')
set_prio('Blanketing Robes of Snow', 'Ethos > OS', 'BiS: Disc', '')
set_prio('Tunic of the Artifact Guardian', 'RFI', 'Check what mindblown is using, 4pc + off chest or 4pc + off gloves', 'Cluelust')
set_prio('Arcanic Tramplers', 'MS>OS Roll', 'BiS: Disc, Spriest, Arcane, Demo, Aff, Balance, RDruid', 'Azz')
set_prio('Boots of Healing Energies', 'Sterile', '', 'Saicere')
set_prio('Winter Spectacle Gloves', 'Cluelust > RFI', 'BiS RSham non-tier gloves', '')
set_prio('Hood of Rationality', 'Zlips > RFI', 'BiS Disc, Spriest (and Fire)', 'Zeforr, Ethos')
set_prio('Leggings of the Wanton Spellcaster', 'Thor', 'BiS for every caster dps except maybe Arcane', '')
set_prio('Legplates of Sovereignty', 'Hawkey', 'BiS: Blood and Prot', 'Fig')
set_prio('Elevated Lair Pauldrons', 'RFI > OS', 'Filler', 'Fig')
set_prio('Mantle of Dissemination', 'Zeforr > RFI', 'Bis shadow', 'Zlips')
set_prio('Spaulders of Catatonia', 'Balance > OS', 'Filler', '')
set_prio('Living Ice Crystals', 'MS>OS Roll', 'A bit shit', '')
set_prio('Leash of Heedless Magic', 'Heasy', 'BiS Disc, Spriest, Arcane, Balance, RDruid', 'Jules')
set_prio('Unravelling Strands of Sanity', 'RDruid > OS', 'Filler', '')
set_prio('Reins of the Azure Drake', 'Tobs for making this sick addon', '', '')