# This is a basic workflow to help you get started with Actions

name: Package Addon

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout addon
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q

      - name: Package and release
        uses: BigWigsMods/packager@v2
