# This is a basic workflow to help you get started with Actions

name: Check LUA on Pull

on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v3

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q
